# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

if {[catch {
    package ifneeded multiseq 2.0 "set env(VERSIONDIR) {$dir}\n[list source [file join $dir multiseq.tcl]]\n[list source [file join $dir stamp_options.tcl]]\n[list source [file join $dir phylotree_options.tcl]]\n[list source [file join $dir select_residues.tcl]]\n[list source [file join $dir select_contactshell.tcl]]\n[list source [file join $dir select_nrset.tcl]]\n[list source [file join $dir import_options.tcl]]\n[list source [file join $dir export_options.tcl]]\n[list source [file join $dir colormap_vmd.tcl]]\n[list source [file join $dir plot.tcl]]\n[list source [file join $dir get_input.tcl]]\n[list source [file join $dir find.tcl]]"
} errorMessage] != 0} {
    
    global errorInfo
    set callStack [list "MultiSeq Error) " $errorInfo]
    puts [join $callStack "\n"]
}

