# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded seqdata 1.0 "[list source [file join $dir seqdata.tcl]]\n[list source [file join $dir seqdata_aln.tcl]]\n[list source [file join $dir seqdata_fasta.tcl]]\n[list source [file join $dir seqdata_vmd.tcl]]\n[list source [file join $dir seqdata_swissprot.tcl]]\n[list source [file join $dir seqdata_pdb.tcl]]\n[list source [file join $dir seqdata_taxonomy.tcl]]\n[list source [file join $dir seqdata_notes.tcl]]\n[list source [file join $dir seqdata_scop.tcl]]\n[list source [file join $dir seqdata_genbank.tcl]]\n[list source [file join $dir seqdata_astral.tcl]]\n[list source [file join $dir seqdata_enzyme.tcl]]\n[list source [file join $dir seqdata_nex.tcl]]\n[list source [file join $dir seqdata_pir.tcl]]\n[list source [file join $dir seqdata_phy.tcl]]"

