# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded seqedit 1.0 "set env(BLOSUMDIR) {$dir/blosum}; [list source [file join $dir clustalw_preferences.tcl]]\n[list source [file join $dir seqedit.tcl]]\n[list source [file join $dir customize_groups.tcl]]\n[list source [file join $dir colormap_default.tcl]]\n[list source [file join $dir get_groupname.tcl]]\n[list source [file join $dir metric_conservation.tcl]]\n[list source [file join $dir metric_type.tcl]]\n[list source [file join $dir metric_percentid.tcl]]\n[list source [file join $dir metric_selection.tcl]]\n[list source [file join $dir metric_import.tcl]]\n[list source [file join $dir metric_element.tcl]]\n[list source [file join $dir metric_entropy.tcl]]\n[list source [file join $dir metric_insertions.tcl]]\n[list source [file join $dir metric_similarity.tcl]]\n[list source [file join $dir removegaps_options.tcl]]\n[list source [file join $dir taxonomy_options.tcl]]"
package ifneeded seqedit_preview 1.0 [list source [file join $dir seqedit_preview.tcl]]
package ifneeded seqedit_widget 1.0 [list source [file join $dir seqedit_widget_select.tcl]]\n[list source [file join $dir seqedit_widget_edit.tcl]]\n[list source [file join $dir seqedit_widget_statusbar.tcl]]\n[list source [file join $dir seqedit_widget.tcl]]
