# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded autoionize 1.1 "[list tclPkgSetup $dir autoionize 1.1 {{autoionize.tcl source {autoionize autoionize_core autoionize_usage}}}] ; set env(AUTOIONIZEDIR) [list $dir]"
package ifneeded autoionizegui 1.0 [list source [file join $dir autoionizegui.tcl]]
