fpocket: aa.h File Reference
aa.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Data Structures
struct s_amino_a
Defines
#define M_NB_AA 20
#define M_ALA_IDX 0
#define M_CYS_IDX 1
#define M_ASP_IDX 2
#define M_GLU_IDX 3
#define M_PHE_IDX 4
#define M_GLY_IDX 5
#define M_HIS_IDX 6
#define M_ILE_IDX 7
#define M_LYS_IDX 8
#define M_LEU_IDX 9
#define M_MET_IDX 10
#define M_ASN_IDX 11
#define M_PRO_IDX 12
#define M_GLN_IDX 13
#define M_ARG_IDX 14
#define M_SER_IDX 15
#define M_THR_IDX 16
#define M_VAL_IDX 17
#define M_TRP_IDX 18
#define M_TYR_IDX 19
Functions
int get_aa_index (const char *name)
char * get_aa_name3 (const int index)
float get_aa_mw (const char *name)
float get_aa_volume_score (const char *name)
float get_aa_hydrophobicity_score (const char *name)
int get_aa_charge (const char *name)
int get_aa_polarity (const char *name)
int get_aa_func_grp (const char *name)
float get_volume_score_from_idx (int aa_index)
float get_hydrophobicity_score_from_idx (int aa_index)
int get_charge_from_idx (int aa_index)
int get_polarity_from_idx (int aa_index)
int get_func_grp_from_idx (int aa_index)
Define Documentation
#define M_ALA_IDX 0
0 for ALA
Definition at line 44 of file aa.h.
Referenced by set_aa_desc().
#define M_ARG_IDX 14
14 for ARG
Definition at line 58 of file aa.h.
Referenced by set_aa_desc().
#define M_ASN_IDX 11
11 for ASN
Definition at line 55 of file aa.h.
Referenced by set_aa_desc().
#define M_ASP_IDX 2
2 for ASP
Definition at line 46 of file aa.h.
Referenced by set_aa_desc().
#define M_CYS_IDX 1
1 for CYS
Definition at line 45 of file aa.h.
Referenced by set_aa_desc().
#define M_GLN_IDX 13
13 for GLN
Definition at line 57 of file aa.h.
Referenced by set_aa_desc().
#define M_GLU_IDX 3
3 for GLU
Definition at line 47 of file aa.h.
Referenced by set_aa_desc().
#define M_GLY_IDX 5
5 for GLY
Definition at line 49 of file aa.h.
Referenced by set_aa_desc().
#define M_HIS_IDX 6
6 for HIS
Definition at line 50 of file aa.h.
Referenced by set_aa_desc().
#define M_ILE_IDX 7
7 for ILE
Definition at line 51 of file aa.h.
Referenced by set_aa_desc().
#define M_LEU_IDX 9
9 for LEU
Definition at line 53 of file aa.h.
Referenced by set_aa_desc().
#define M_LYS_IDX 8
8 for LYS
Definition at line 52 of file aa.h.
Referenced by set_aa_desc().
#define M_MET_IDX 10
10 for MET
Definition at line 54 of file aa.h.
Referenced by set_aa_desc().
#define M_NB_AA 20
number of amino acid macros
Definition at line 43 of file aa.h.
Referenced by get_aa_index(), and print_pocket().
#define M_PHE_IDX 4
4 for PHE
Definition at line 48 of file aa.h.
Referenced by set_aa_desc().
#define M_PRO_IDX 12
12 for PRO
Definition at line 56 of file aa.h.
Referenced by set_aa_desc().
#define M_SER_IDX 15
15 for SER
Definition at line 59 of file aa.h.
Referenced by set_aa_desc().
#define M_THR_IDX 16
16 for THR
Definition at line 60 of file aa.h.
Referenced by set_aa_desc().
#define M_TRP_IDX 18
18 for TRP
Definition at line 62 of file aa.h.
Referenced by set_aa_desc().
#define M_TYR_IDX 19
19 for TYR
Definition at line 63 of file aa.h.
Referenced by set_aa_desc().
#define M_VAL_IDX 17
17 for VAL
Definition at line 61 of file aa.h.
Referenced by set_aa_desc().
Function Documentation
int get_aa_charge (const char * name)
## FUNCTION: get_aa_charge
## SPECIFICATION: Return the charge score of given amino acid
## PARAMETRES: const char *name: Amno acid name (3 letter code representation)
## RETURN: charge (positiv, negativ, neutral, see header for more details), 0 if aa not found in the tab
Definition at line 258 of file aa.c.
References s_amino_a::charge, and get_aa_index().
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].charge ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return 0 ;
}
int get_aa_func_grp (const char * name)
## FUNCTION: get_func_grp_from_idx
## SPECIFICATION: Return the functional group type of the given amino acid
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: int: functional group id
Definition at line 314 of file aa.c.
References s_amino_a::func_grp, and get_aa_index().
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].func_grp ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1 ;
}
float get_aa_hydrophobicity_score (const char * name)
## FUNCTION: get_aa_hydrophobicity_score
## SPECIFICATION: Return the hydrophobicity score of given amino acid
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: float: hydrophobicity score, -1 if aa not found in the tab
Definition at line 229 of file aa.c.
References get_aa_index(), and s_amino_a::hydrophobicity.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].hydrophobicity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1.0 ;
}
int get_aa_index (const char * name)
## FUNCTION: get_aa_index
## SPECIFICATION: Return the index of AA given in argument (3letter code representation) in the static AA tab.
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: int: index of the given amino acid, -1 if not found in the tab
Definition at line 140 of file aa.c.
References M_NB_AA.
Referenced by get_aa_charge(), get_aa_func_grp(), get_aa_hydrophobicity_score(), get_aa_mw(), get_aa_polarity(), and get_aa_volume_score().
{
        int i,
                aa_index = -1 ;
        for(i = 0 ; i < M_NB_AA ; i++) {
                if(toupper(name[0]) == ST_aa[i].name3[0] && toupper(name[1]) == ST_aa[i].name3[1]
                && toupper(name[2]) == ST_aa[i].name3[2]   ) {
                        aa_index = i ;
                        break ;
                }
        }
        return aa_index ;
}
float get_aa_mw (const char * name)
## FUNCTION: get_aa_mw
## SPECIFICATION: Return the molecular weight of AA given in argument
## PARAMETRES: @ const int index: Index of the AA in the tab
## RETURN: float: Molecular weight if the index is valid, NULL if not.
Definition at line 173 of file aa.c.
References get_aa_index(), and s_amino_a::mw.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].mw ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1.0 ;
}
char* get_aa_name3 (const int index)
## FUNCTION: get_aa_name3
## SPECIFICATION: Return the name of AA given in argument (index in the static table)
## PARAMETRES: @ const int index: Index of the AA in the tab
## RETURN: char *: Name if index is valid, NULL if not.
Definition at line 117 of file aa.c.
References s_amino_a::name3.
Referenced by dpocket(), and mdpocket_characterize().
{
        if(index < M_NB_AA && index >= 0) {
                return (char*)ST_aa[index].name3 ;
        }
        return NULL ;
}
int get_aa_polarity (const char * name)
## FUNCTION: get_aa_polarity
## SPECIFICATION: Return the polarity score of given amino acid
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: int polarity (polar, apolar), 0 if aa not found in the tab
Definition at line 286 of file aa.c.
References get_aa_index(), and s_amino_a::polarity.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].polarity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1 ;
}
float get_aa_volume_score (const char * name)
## FUNCTION: get_aa_volume_score
## SPECIFICATION: Return the volume score of given amino acid (very approximative...)
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: float: volume score, -1 if aa not found in the tab
Definition at line 201 of file aa.c.
References get_aa_index(), and s_amino_a::volume.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].volume ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1.0 ;
}
int get_charge_from_idx (int aa_index)
## FUNCTION: get_charge_from_idx
## SPECIFICATION: Return the charge score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: int charge (positiv, negativ, neutral, see header for more details), 0 if aa not found in the tab
Definition at line 399 of file aa.c.
References s_amino_a::charge.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0){
                return ST_aa[aa_index].charge ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return 0 ;
}
int get_func_grp_from_idx (int aa_index)
## FUNCTION: get_func_grp_from_idx
## SPECIFICATION: Return the functional group type of the given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: int: functional group id
Definition at line 451 of file aa.c.
References s_amino_a::func_grp.
{
        if(aa_index < M_NB_AA && aa_index >= 0) {
                return ST_aa[aa_index].func_grp ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1 ;
}
float get_hydrophobicity_score_from_idx (int aa_index)
## FUNCTION: get_hydrophobicity_score_from_idx
## SPECIFICATION: Return the hydrophobicity score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: float hydrophobicity score, -1 if aa not found in the tab
Definition at line 372 of file aa.c.
References s_amino_a::hydrophobicity.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0) {
                return ST_aa[aa_index].hydrophobicity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1.0 ;
}
int get_polarity_from_idx (int aa_index)
## FUNCTION: get_polarity_from_idx
## SPECIFICATION: Return the polarity score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: int: polarity (polar, apolar), -1 if aa not found in the tab
Definition at line 425 of file aa.c.
References s_amino_a::polarity.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0) {
                return ST_aa[aa_index].polarity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1 ;
}
float get_volume_score_from_idx (int aa_index)
## FUNCTION: get_volume_score_from_idx
## SPECIFICATION: Return the volume score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: float: volume score, -1 if aa not found in the tab
Definition at line 346 of file aa.c.
References s_amino_a::volume.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0){
                return ST_aa[aa_index].volume ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1.0 ;
}