fpocket: dpmain.c File Reference
dpmain.c File Reference
#include "../headers/dpmain.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
## FUNCTION: int main(int argc, char *argv[])
## SPECIFICATION: Main program for dpocket!
Definition at line 67 of file dpmain.c.
References dpocket(), free_all(), free_dparams(), and get_dpocket_args().
{
        s_dparams *par = get_dpocket_args(argc, argv) ;
        //print_dparams(par, stdout) ;
        dpocket(par) ;
        free_dparams(par) ;
        free_all() ;
        return 0 ;
}