fpocket: fpmain.c File Reference
fpmain.c File Reference
#include "../headers/fpmain.h"
Functions
int main (int argc, char *argv[])
void process_pdb (char *pdbname, s_fparams *params)
Function Documentation
int main (int argc, char * argv[])
## FUNCTION: int main(int argc, char *argv[])
## SPECIFICATION: Main program!
Definition at line 71 of file fpmain.c.
References s_fparams::db_run, free_all(), free_fparams(), get_fpocket_args(), s_fparams::npdb, s_fparams::pdb_lst, s_fparams::pdb_path, print_pocket_usage(), and process_pdb().
{
        s_fparams *params = get_fpocket_args(argc, argv) ;
        if(!params->db_run) fprintf(stdout, "***** POCKET HUNTING BEGINS ***** \n") ;
        /* If parameters parsing is ok */
        if(params) {
                if(params->pdb_lst != NULL) {
                /* Handle a list of pdb */
                        int i ;
            for (i = 0 ; i < params->npdb ; i++) {
                                printf("> Protein %d / %d : %s", i, params->npdb,
                                                                                                   params->pdb_lst[i]) ;
                                if(i == params->npdb - 1) fprintf(stdout, "\n") ;
                                else fprintf(stdout, "\r") ;
                                fflush(stdout) ;
                process_pdb(params->pdb_lst[i], params) ;
            }
        }
        else {
                if(params->pdb_path == NULL || strlen(params->pdb_path) <= 0) {
                        fprintf(stdout, "! Invalid pdb name given.\n");
                        print_pocket_usage(stdout) ;
                }
                else {
                        process_pdb(params->pdb_path, params) ;
                }
        }
                free_fparams(params) ;
        }
        else {
                print_pocket_usage(stdout) ;
        }
        if(!params->db_run)fprintf(stdout, "***** POCKET HUNTING ENDS ***** \n") ;
        free_all() ;
        return 0;
}
void process_pdb (char * pdbname, s_fparams * params)
## FUNCTION: process_pdb
## SPECIFICATION: Handle a single pdb: check the pdb name, load data, and launch fpocket if the pdb file have been successfully read.
## PARAMETRES: @ char *pdbname : Name of the pdb @ s_fparams *params : Parameters of the algorithm. See fparams.c/.h
## RETURN: void
Definition at line 130 of file fpmain.c.
References c_lst_pocket_free(), s_fparams::db_run, s_pdb::fpdb, M_DONT_KEEP_LIG, M_KEEP_LIG, M_MAX_PDB_NAME_LEN, rpdb_open(), rpdb_read(), search_pocket(), write_descriptors_DB(), write_out_fpocket(), and write_out_fpocket_DB().
Referenced by main().
{
        /* Check the PDB file */
        if(pdbname == NULL) return ;
        int len = strlen(pdbname) ;
        if(len >= M_MAX_PDB_NAME_LEN || len <= 0) {
                fprintf(stderr, "! Invalid length for the pdb file name. (Max: %d, Min 1)\n",
                                M_MAX_PDB_NAME_LEN) ;
                return ;
        }
        /* Try to open it */
        s_pdb *pdb =  rpdb_open(pdbname, NULL, M_DONT_KEEP_LIG) ;
        s_pdb *pdb_w_lig =  rpdb_open(pdbname, NULL, M_KEEP_LIG) ;
        if(pdb) {
                /* Actual reading of pdb data and then calculation */
                        rpdb_read(pdb, NULL, M_DONT_KEEP_LIG) ;
                        rpdb_read(pdb_w_lig, NULL, M_KEEP_LIG) ;
                        c_lst_pockets *pockets = search_pocket(pdb, params,pdb_w_lig);
                        if(pockets) {
                                if(params->db_run) {
                                    write_descriptors_DB(pockets,stdout);
                                    write_out_fpocket_DB(pockets, pdb, pdbname);
                                }
                                else write_out_fpocket(pockets, pdb, pdbname);
                                c_lst_pocket_free(pockets) ;
                        }
                        fclose(pdb->fpdb);
        }
        else fprintf(stderr, "! PDB reading failed!\n");
}