fpocket: tpmain.c File Reference
tpmain.c File Reference
#include "../headers/tpmain.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
## FUNCTION: int main(int argc, char *argv[])
## SPECIFICATION: Main program for tpocket!
Definition at line 63 of file tpmain.c.
References free_all(), free_tparams(), get_tpocket_args(), s_tparams::nfiles, and test_fpocket().
{
        s_tparams *par = get_tpocket_args(argc, argv) ;
        if(par && par->nfiles > 0) {
                test_fpocket(par) ;
        }
        free_tparams(par) ;
        free_all() ;
        return 0 ;
}