# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded phylotree 1.1 "[list source [file join $dir phylotree.tcl]]\n[list source [file join $dir phylotree_analysis.tcl]]\n[list source [file join $dir phylotree_data.tcl]]\n[list source [file join $dir phylotree_export.tcl]]\n[list source [file join $dir phylotree_je.tcl]]\n[list source [file join $dir phylotree_matrixviewer.tcl]]\n[list source [file join $dir phylotree_newick.tcl]]\n[list source [file join $dir phylotree_nexus.tcl]]\n[list source [file join $dir phylotree_nodeprops.tcl]]\n[list source [file join $dir phylotree_widget.tcl]]"
package ifneeded upgma_cluster 1.2 "set env(UPGMA_CLUSTERPLUGINDIR) {$dir}; [list source [file join $dir cluster.tcl]]"

