# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded fftpack     1.1 [list source [file join $dir fftpack.tcl]]
package ifneeded fftcmds     1.1 [list load   [file join $dir fftcmds.so ]]
package ifneeded sgsmooth    1.1 [list load   [file join $dir sgsmooth.so]]
package ifneeded signalproc  1.1 [list source [file join $dir signalproc.tcl]]
package ifneeded specden     1.1 [list load   [file join $dir specden.so]]
package ifneeded data_io_lib 1.1 [list source [file join $dir data_io_lib.tcl]]

