fpocket: aa.c File Reference
aa.c File Reference
#include "../headers/aa.h"
Functions
char * get_aa_name3 (const int index)
int get_aa_index (const char *name)
float get_aa_mw (const char *name)
float get_aa_volume_score (const char *name)
float get_aa_hydrophobicity_score (const char *name)
int get_aa_charge (const char *name)
int get_aa_polarity (const char *name)
int get_aa_func_grp (const char *name)
float get_volume_score_from_idx (int aa_index)
float get_hydrophobicity_score_from_idx (int aa_index)
int get_charge_from_idx (int aa_index)
int get_polarity_from_idx (int aa_index)
int get_func_grp_from_idx (int aa_index)
Variables
static const s_amino_a ST_aa [20]
Function Documentation
int get_aa_charge (const char * name)
## FUNCTION: get_aa_charge
## SPECIFICATION: Return the charge score of given amino acid
## PARAMETRES: const char *name: Amno acid name (3 letter code representation)
## RETURN: charge (positiv, negativ, neutral, see header for more details), 0 if aa not found in the tab
Definition at line 258 of file aa.c.
References s_amino_a::charge, and get_aa_index().
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].charge ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return 0 ;
}
int get_aa_func_grp (const char * name)
## FUNCTION: get_func_grp_from_idx
## SPECIFICATION: Return the functional group type of the given amino acid
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: int: functional group id
Definition at line 314 of file aa.c.
References s_amino_a::func_grp, and get_aa_index().
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].func_grp ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1 ;
}
float get_aa_hydrophobicity_score (const char * name)
## FUNCTION: get_aa_hydrophobicity_score
## SPECIFICATION: Return the hydrophobicity score of given amino acid
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: float: hydrophobicity score, -1 if aa not found in the tab
Definition at line 229 of file aa.c.
References get_aa_index(), and s_amino_a::hydrophobicity.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].hydrophobicity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1.0 ;
}
int get_aa_index (const char * name)
## FUNCTION: get_aa_index
## SPECIFICATION: Return the index of AA given in argument (3letter code representation) in the static AA tab.
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: int: index of the given amino acid, -1 if not found in the tab
Definition at line 140 of file aa.c.
References M_NB_AA.
Referenced by get_aa_charge(), get_aa_func_grp(), get_aa_hydrophobicity_score(), get_aa_mw(), get_aa_polarity(), and get_aa_volume_score().
{
        int i,
                aa_index = -1 ;
        for(i = 0 ; i < M_NB_AA ; i++) {
                if(toupper(name[0]) == ST_aa[i].name3[0] && toupper(name[1]) == ST_aa[i].name3[1]
                && toupper(name[2]) == ST_aa[i].name3[2]   ) {
                        aa_index = i ;
                        break ;
                }
        }
        return aa_index ;
}
float get_aa_mw (const char * name)
## FUNCTION: get_aa_mw
## SPECIFICATION: Return the molecular weight of AA given in argument
## PARAMETRES: @ const int index: Index of the AA in the tab
## RETURN: float: Molecular weight if the index is valid, NULL if not.
Definition at line 173 of file aa.c.
References get_aa_index(), and s_amino_a::mw.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].mw ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1.0 ;
}
char* get_aa_name3 (const int index)
## FUNCTION: get_aa_name3
## SPECIFICATION: Return the name of AA given in argument (index in the static table)
## PARAMETRES: @ const int index: Index of the AA in the tab
## RETURN: char *: Name if index is valid, NULL if not.
Definition at line 117 of file aa.c.
References s_amino_a::name3.
Referenced by dpocket(), and mdpocket_characterize().
{
        if(index < M_NB_AA && index >= 0) {
                return (char*)ST_aa[index].name3 ;
        }
        return NULL ;
}
int get_aa_polarity (const char * name)
## FUNCTION: get_aa_polarity
## SPECIFICATION: Return the polarity score of given amino acid
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: int polarity (polar, apolar), 0 if aa not found in the tab
Definition at line 286 of file aa.c.
References get_aa_index(), and s_amino_a::polarity.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].polarity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1 ;
}
float get_aa_volume_score (const char * name)
## FUNCTION: get_aa_volume_score
## SPECIFICATION: Return the volume score of given amino acid (very approximative...)
## PARAMETRES: @ const char *name: Amno acid name (3 letter code representation)
## RETURN: float: volume score, -1 if aa not found in the tab
Definition at line 201 of file aa.c.
References get_aa_index(), and s_amino_a::volume.
{
        int aa_index = get_aa_index(name) ;
        if(aa_index != -1) {
                return ST_aa[aa_index].volume ;
        }/*
        else {
                fprintf(stderr, "! Amino acid '%s' could not be found in property table...\n", name);
        }*/
        return -1.0 ;
}
int get_charge_from_idx (int aa_index)
## FUNCTION: get_charge_from_idx
## SPECIFICATION: Return the charge score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: int charge (positiv, negativ, neutral, see header for more details), 0 if aa not found in the tab
Definition at line 399 of file aa.c.
References s_amino_a::charge.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0){
                return ST_aa[aa_index].charge ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return 0 ;
}
int get_func_grp_from_idx (int aa_index)
## FUNCTION: get_func_grp_from_idx
## SPECIFICATION: Return the functional group type of the given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: int: functional group id
Definition at line 451 of file aa.c.
References s_amino_a::func_grp.
{
        if(aa_index < M_NB_AA && aa_index >= 0) {
                return ST_aa[aa_index].func_grp ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1 ;
}
float get_hydrophobicity_score_from_idx (int aa_index)
## FUNCTION: get_hydrophobicity_score_from_idx
## SPECIFICATION: Return the hydrophobicity score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: float hydrophobicity score, -1 if aa not found in the tab
Definition at line 372 of file aa.c.
References s_amino_a::hydrophobicity.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0) {
                return ST_aa[aa_index].hydrophobicity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1.0 ;
}
int get_polarity_from_idx (int aa_index)
## FUNCTION: get_polarity_from_idx
## SPECIFICATION: Return the polarity score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: int: polarity (polar, apolar), -1 if aa not found in the tab
Definition at line 425 of file aa.c.
References s_amino_a::polarity.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0) {
                return ST_aa[aa_index].polarity ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1 ;
}
float get_volume_score_from_idx (int aa_index)
## FUNCTION: get_volume_score_from_idx
## SPECIFICATION: Return the volume score of given amino acid
## PARAMETRES: @ int aa_index: Index of the amino acid in the tab
## RETURN: float: volume score, -1 if aa not found in the tab
Definition at line 346 of file aa.c.
References s_amino_a::volume.
Referenced by set_aa_desc().
{
        if(aa_index < M_NB_AA && aa_index >= 0){
                return ST_aa[aa_index].volume ;
        }/*
        else {
                fprintf(stderr, "! Amino acid %d could not be found in property table...\n", aa_index);
        }*/
        return -1.0 ;
}
Variable Documentation
const s_amino_a ST_aa[20] [static]
Initial value:
{
        { "ALA", 'A',  89.0, 2.0,  41.0,  0, 0, 2 },
        { "ARG", 'R', 174.0, 7.0, -14.0,  1, 1, 5 },
        { "ASN", 'N', 132.0, 3.0, -28.0,  0, 1, 3 },
        { "ASP", 'D', 133.0, 3.0, -55.0, -1, 1, 3 },
        { "CYS", 'C', 121.0, 3.0,  49.0,  0, 0, 6 },
        { "GLN", 'Q', 146.0, 4.0, -10.0,  0, 1, 3 },
        { "GLU", 'E', 147.0, 4.0, -31.0, -1, 1, 3 },
        { "GLY", 'G',  75.0, 1.0,   0.0,  0, 0, 2 },
        { "HIS", 'H', 155.0, 4.0,   8.0,  1, 1, 1 },
        { "ILE", 'I', 131.0, 5.0,  99.0,  0, 0, 2 },
        { "LEU", 'L', 131.0, 5.0,  97.0,  0, 0, 2 },
        { "LYS", 'K', 146.0, 6.0, -23.0,  1, 1, 5 },
        { "MET", 'M', 149.0, 5.0,  74.0,  0, 0, 5 },
        { "PHE", 'F', 165.0, 6.0, 100.0,  0, 0, 1 },
        { "PRO", 'P', 115.0, 3.0, -46.0,  0, 0, 2 },
        { "SER", 'S', 105.0, 2.0,  -5.0,  0, 1, 4 },
        { "THR", 'T', 119.0, 3.0,  13.0,  0, 1, 4 },
        { "TRP", 'W', 204.0, 8.0,  97.0,  0, 1, 1 },
        { "TYR", 'Y', 181.0, 7.0,  63.0,  0, 1, 1 },
        { "VAL", 'V', 117.0, 4.0,  76.0,  0, 0, 2 }
}
Several amino-acid properties, taken from: http://www.info.univ-angers.fr/~gh/Idas/proprietes.htm
Hydrophobicity taken from : http://www.sigmaaldrich.com/Area_of_Interest/Biochemicals/PolyAmino_Acids/Reference_Chart.html
Monera & al. Journal of Protein Science 1, 319-329 (1995)
Molecular weight taken from: http://www.expasy.ch/tools/pscale/Molecularweight.html
Definition at line 78 of file aa.c.