fpocket: dparams.h File Reference
dparams.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <assert.h>
#include "utils.h"
#include "memhandler.h"
#include "fparams.h"
Data Structures
struct s_dparams
Defines
#define M_DPAR_INTERFACE_METHOD1 'e'
#define M_DPAR_INTERFACE_METHOD2 'E'
#define M_DPAR_DISTANCE_CRITERIA 'd'
#define M_DPAR_INPUT_FILE 'f'
#define M_DPAR_OUTPUT_FILE 'o'
#define M_INTERFACE_METHOD1 1
#define M_VERT_LIG_NEIG_DIST 4.0
#define M_INTERFACE_METHOD2 2
#define M_LIG_NEIG_DIST 4.0
#define M_OUTPUT_FILE1_DEFAULT "dpout_explicitp.txt"
#define M_OUTPUT_FILE2_DEFAULT "dpout_fpocketp.txt"
#define M_OUTPUT_FILE3_DEFAULT "dpout_fpocketnp.txt"
#define M_MAX_FILE_NAME_LENGTH 300
#define M_NB_MC_ITER 2500
#define M_MIN_ASPH_RAY 2.8
#define M_MAX_ASPH_RAY 10.0
#define M_DP_USAGE "\\n***** USAGE (dpocket) *****\n\\n\The program needs as input a file containing at each \n\line a pdb file name and a ligand code (3 letters). \n\The format of each line must be: \n\n\{PATH/}2fej.pdb LIG \n\n\The ligand code is the resname of the ligand atoms in \n\the pdb file and has to separated by a tab from the \n\pdb structure in the input file. \n\n\See the manual for more information. \n\n\Example of command using default parameters: \n\\t./bin/dpocket -f file_path \n\n\Options: \n\\t-o string : Prefix of the output file. (./dpout_*) \n\\t-e : Use the first protein-ligand explicit \n\\t interface definition (default). \n\\t-E : Use the second protein-ligand explicit \n\\t interface definition. \n\\t-d float : Distance criteria for the choosen \n\\t interface definition. (4.0) \n\n\Options specific to fpocket are usable too. \n\See the manual/tutorial for mor information. \n\***************************\n"
Functions
s_dparams * init_def_dparams (void)
s_dparams * get_dpocket_args (int nargs, char **args)
int add_list_complexes (char *str_list_file, s_dparams *par)
int add_complexe (char *complex, char *ligand, s_dparams *par)
int parse_dist_crit (char *str, s_dparams *p)
void print_dparams (s_dparams *p, FILE *f)
void print_dpocket_usage (FILE *f)
void free_dparams (s_dparams *p)
Define Documentation
#define M_DP_USAGE "\\n***** USAGE (dpocket) *****\n\\n\The program needs as input a file containing at each \n\line a pdb file name and a ligand code (3 letters). \n\The format of each line must be: \n\n\{PATH/}2fej.pdb LIG \n\n\The ligand code is the resname of the ligand atoms in \n\the pdb file and has to separated by a tab from the \n\pdb structure in the input file. \n\n\See the manual for more information. \n\n\Example of command using default parameters: \n\\t./bin/dpocket -f file_path \n\n\Options: \n\\t-o string : Prefix of the output file. (./dpout_*) \n\\t-e : Use the first protein-ligand explicit \n\\t interface definition (default). \n\\t-E : Use the second protein-ligand explicit \n\\t interface definition. \n\\t-d float : Distance criteria for the choosen \n\\t interface definition. (4.0) \n\n\Options specific to fpocket are usable too. \n\See the manual/tutorial for mor information. \n\***************************\n"
Definition at line 78 of file dparams.h.
Referenced by print_dpocket_usage().
#define M_DPAR_DISTANCE_CRITERIA 'd'
Definition at line 56 of file dparams.h.
Referenced by get_dpocket_args().
#define M_DPAR_INPUT_FILE 'f'
Definition at line 57 of file dparams.h.
Referenced by get_dpocket_args().
#define M_DPAR_INTERFACE_METHOD1 'e'
COPYRIGHT DISCLAIMER
Vincent Le Guilloux, Peter Schmidtke and Pierre Tuffery, hereby disclaim all copyright interest in the program “fpocket” (which performs protein cavity detection) written by Vincent Le Guilloux and Peter Schmidtke.
Vincent Le Guilloux 28 November 2008 Peter Schmidtke 28 November 2008 Pierre Tuffery 28 November 2008
GNU GPL
This file is part of the fpocket package.
fpocket is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
fpocket is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with fpocket. If not, see <http://www.gnu.org/licenses/>.
Definition at line 54 of file dparams.h.
Referenced by get_dpocket_args().
#define M_DPAR_INTERFACE_METHOD2 'E'
Definition at line 55 of file dparams.h.
Referenced by get_dpocket_args().
#define M_DPAR_OUTPUT_FILE 'o'
Definition at line 58 of file dparams.h.
Referenced by get_dpocket_args().
#define M_INTERFACE_METHOD1 1
Definition at line 63 of file dparams.h.
Referenced by get_dpocket_args(), init_def_dparams(), and print_dparams().
#define M_INTERFACE_METHOD2 2
Definition at line 66 of file dparams.h.
Referenced by get_dpocket_args(), and get_explicit_desc().
#define M_LIG_NEIG_DIST 4.0
Definition at line 67 of file dparams.h.
Referenced by get_dpocket_args(), and init_def_tparams().
#define M_MAX_ASPH_RAY 10.0
Definition at line 76 of file dparams.h.
#define M_MAX_FILE_NAME_LENGTH 300
Definition at line 73 of file dparams.h.
Referenced by get_dpocket_args(), get_mdpocket_args(), get_tpocket_args(), init_def_dparams(), init_def_mdparams(), and init_def_tparams().
#define M_MIN_ASPH_RAY 2.8
Definition at line 75 of file dparams.h.
#define M_NB_MC_ITER 2500
Definition at line 74 of file dparams.h.
#define M_OUTPUT_FILE1_DEFAULT "dpout_explicitp.txt"
Definition at line 69 of file dparams.h.
Referenced by init_def_dparams().
#define M_OUTPUT_FILE2_DEFAULT "dpout_fpocketp.txt"
Definition at line 70 of file dparams.h.
Referenced by init_def_dparams().
#define M_OUTPUT_FILE3_DEFAULT "dpout_fpocketnp.txt"
Definition at line 71 of file dparams.h.
Referenced by init_def_dparams().
#define M_VERT_LIG_NEIG_DIST 4.0
Definition at line 64 of file dparams.h.
Referenced by get_dpocket_args(), and init_def_dparams().
Function Documentation
int add_complexe (char * complex, char * ligand, s_dparams * par)
## FUNCTION: add_complexe
## SPECIFICATION: Add a set of data to the list of set of data in the parameters. this function is used for the tpocket program only.
The function will try to open the file, and data will be stored only if the file exists, and if the name of the ligand is valid.
## PARAMETERS: @ char *apo : The apo path @ char *complex : The complex path @ char *ligan : The ligand resname: a 4 letter (max!) @ s_dparams *par: The structure than contains parameters.
## RETURN: int: 1 if everything is OK, 0 if not.
Definition at line 301 of file dparams.c.
References s_dparams::fcomplex, fopen_pdb_check_case(), s_dparams::ligs, my_malloc(), my_realloc(), and s_dparams::nfiles.
Referenced by add_list_complexes().
{
        int nm1, i, l ;
        FILE *f = fopen_pdb_check_case(complex, "r") ;
        if(f) {
                l = strlen(ligand) ;
                if(strlen(ligand) >= 2) {
                        for(i = 0 ; i < l ; i++) ligand[i] = toupper(ligand[i]) ;
                        nm1 = par->nfiles ;
                        par->nfiles += 1 ;
                        par->ligs   = (char**) my_realloc(par->ligs, (par->nfiles)*sizeof(char*)) ;
                        par->fcomplex = (char**) my_realloc(par->fcomplex, (par->nfiles)*sizeof(char*)) ;
                        par->fcomplex[nm1] = (char *)my_malloc((strlen(complex)+1)*sizeof(char)) ;
                        par->ligs[nm1]   = (char *)my_malloc((strlen(ligand)+1)*sizeof(char)) ;
                        strcpy(par->fcomplex[nm1], complex) ;
                        strcpy(par->ligs[nm1], ligand) ;
                        fclose(f) ;
                }
                else {
                        fprintf(stdout, "! The name given for the ligand is invalid or absent.\n") ;
                        fclose(f) ;
                        return 0 ;
                }
        }
        else {
                fprintf(stdout, "! The pdb file '%s' doesn't exists.\n", complex) ;
                return 0 ;
        }
        return 1 ;
}
int add_list_complexes (char * str_list_file, s_dparams * par)
## FUNCTION: add_list_complexes
## SPECIFICATION: Load a list of protein-ligand pdb file path. This file should have the following format:
complex_pdb_file ligand_code complex_pdb_file2 ligand_code2 complex_pdb_file3 ligand_code3 (...)
Each complexe-ligand set will be stored in the parameters structure.
## PARAMETRES: @ char *str_list_file : Path of the file containing all data @ s_dparams *par : Structures that stores all thoses files
## RETURN: int: Number of file read.
Definition at line 234 of file dparams.c.
References add_complexe(), M_MAX_PDB_NAME_LEN, and s_dparams::nfiles.
Referenced by get_dpocket_args().
{
        FILE *f;
        int n,
                nread = 0,
                status ;
        char buf[M_MAX_PDB_NAME_LEN*2 + 6],
                 complexbuf[M_MAX_PDB_NAME_LEN],
                 ligbuf[5];
        /* Loading data. */
        f = fopen(str_list_file, "r") ;
/*
        printf(str_list_file);
*/
        if(f) {
                while(fgets(buf, 210, f)) {
/*
                        printf("B: %s\n" , buf);
*/
                        n = par->nfiles ;
                        status = sscanf(buf, "%s\t%s", complexbuf, ligbuf) ;
                        if(status < 2) {
/*
                                fprintf(stderr, "! Skipping row '%s' with bad format (status %d).\n",
                                                                buf, status) ;
*/
                        }
                        else {
/*
                                printf("%s %s\n", complexbuf, ligbuf );
*/
                                nread += add_complexe(complexbuf, ligbuf, par) ;
                        }
                }
        }
        else {
                fprintf(stderr, "! File %s doesn't exists\n", str_list_file) ;
        }
        return nread ;
}
void free_dparams (s_dparams * p)
## FUNCTION: free_params
## SPECIFICATION: Free parameters
## PARAMETRES: @ s_dparams *p: Pointer to the structure to free
## RETURN: void
Definition at line 440 of file dparams.c.
References s_dparams::f_exp, s_dparams::f_fpcknp, s_dparams::f_fpckp, s_dparams::fcomplex, s_dparams::fpar, free_fparams(), s_dparams::ligs, and my_free().
Referenced by get_dpocket_args(), and main().
{
        if(p) {
                if(p->ligs) {
                        my_free(p->ligs) ;
                        p->ligs = NULL ;
                }
                if(p->fcomplex) {
                        my_free(p->fcomplex) ;
                        p->fcomplex = NULL ;
                }
                if(p->f_exp) {
                        my_free(p->f_exp) ;
                        p->f_exp = NULL ;
                }
                if(p->f_fpckp) {
                        my_free(p->f_fpckp) ;
                        p->f_fpckp = NULL ;
                }
                if(p->f_fpcknp) {
                        my_free(p->f_fpcknp) ;
                        p->f_fpcknp = NULL ;
                }
                free_fparams(p->fpar) ;
                my_free(p) ;
        }
}
s_dparams* get_dpocket_args (int nargs, char ** args)
## FUNCTION: get_dpocket_args
## SPECIFICATION: This function analyse the user's command line and parse it to store parameters for the descriptor calculator programm.
## PARAMETRES: @ int nargs : Number of arguments @ char **args : Arguments of main program
## RETURN: s_dparams*: Pointer to parameters
Definition at line 113 of file dparams.c.
References add_list_complexes(), s_dparams::f_exp, s_dparams::f_fpcknp, s_dparams::f_fpckp, s_dparams::fpar, free_dparams(), get_fpocket_args(), init_def_dparams(), s_dparams::interface_dist_crit, s_dparams::interface_method, is_fpocket_opt(), M_DPAR_DISTANCE_CRITERIA, M_DPAR_INPUT_FILE, M_DPAR_INTERFACE_METHOD1, M_DPAR_INTERFACE_METHOD2, M_DPAR_OUTPUT_FILE, M_INTERFACE_METHOD1, M_INTERFACE_METHOD2, M_LIG_NEIG_DIST, M_MAX_FILE_NAME_LENGTH, M_VERT_LIG_NEIG_DIST, parse_dist_crit(), print_dpocket_usage(), and remove_ext().
Referenced by main().
{
        int i,
                status = 0,
                nstats = 0,
                res;
        char *str_list_file = NULL ;
        s_dparams *par = init_def_dparams() ;
        par->fpar = get_fpocket_args(nargs, args) ;
        /* Read arguments by flags */
        for (i = 1; i < nargs; i++) {
                if (strlen(args[i]) == 2 && args[i][0] == '-') {
                        switch (args[i][1]) {
                                case M_DPAR_DISTANCE_CRITERIA :
                                                if(i < nargs-1) status += parse_dist_crit(args[++i], par) ;
                                                else {
                                                        fprintf(stdout, "! Distance criteria defining the protein-ligand interface is missing.\n") ;
                                                        status += 1 ;
                                                }
                                                break ;
                                case M_DPAR_INTERFACE_METHOD1 :
                                                par->interface_method = M_INTERFACE_METHOD1 ;
                                                par->interface_dist_crit = M_VERT_LIG_NEIG_DIST ;
                                                break ;
                                case M_DPAR_INTERFACE_METHOD2 :
                                                par->interface_method = M_INTERFACE_METHOD2 ;
                                                par->interface_dist_crit = M_LIG_NEIG_DIST ;
                                                break ;
                                case M_DPAR_OUTPUT_FILE :
                                                if(nstats >= 1) fprintf(stdout, "! More than one single file for the stats output file has been given. Ignoring this one.\n") ;
                                                else {
                                                        if(i < nargs-1) {
                                                                if(strlen(args[++i]) < M_MAX_FILE_NAME_LENGTH) {
                                                                        remove_ext(args[i]) ;
                                                                        sprintf(par->f_exp, "%s_exp.txt", args[i]) ;
                                                                        sprintf(par->f_fpckp, "%s_fp.txt", args[i]) ;
                                                                        sprintf(par->f_fpcknp, "%s_fpn.txt", args[i]) ;
                                                                }
                                                                else fprintf(stdout, "! Output file name is too long... Keeping default.") ;
                                                        }
                                                        else {
                                                                fprintf(stdout, "! Invalid output file name argument missing.\n") ;
                                                                status += 1 ;
                                                        }
                                                }
                                                break ;
                                case M_DPAR_INPUT_FILE :
                                                if(i < nargs-1) str_list_file = args[++i] ;
                                                else {
                                                        fprintf(stdout, "! Input file name argument missing.\n") ;
                                                        status += 1 ;
                                                }
                                                 break ;
                                default:
                                        //  Check fpocket parameters!
                                        if(!is_fpocket_opt(args[i][1])) {
                                                fprintf(stdout, "> Unknown option '%s'. Ignoring it.\n",
                                                                args[i]) ;
                                        }
                                        break ;
                        }
                }
        }
        if(status > 0) {
                free_dparams(par) ;
                par = NULL ;
                print_dpocket_usage(stdout);
        }
        else {
                if(str_list_file) {
                        res = add_list_complexes(str_list_file, par) ;
                        if(res <= 0) {
                                fprintf(stdout, "! No data has been read.\n") ;
                                free_dparams(par) ;
                                par = NULL ;
                                print_dpocket_usage(stdout);
                        }
                }
                else {
                        fprintf(stdout, "! No input file given... Try again :).\n") ;
                        free_dparams(par) ;
                        par = NULL ;
                        print_dpocket_usage(stdout);
                }
        }
        return par;
}
s_dparams* init_def_dparams (void)
## GENERAL INFORMATION ## ## FILE dparams.c ## AUTHORS P. Schmidtke and V. Le Guilloux ## LAST MODIFIED 28-11-08 ## ## SPECIFICATIONS ## ## Handle parameters (parse the command line and sore values) ## for the dpocket programm. ## ## MODIFICATIONS HISTORY ## ## 28-11-08 (v) Comments UTD + relooking ## 27-11-08 (v) Minor Relooking ## 01-04-08 (v) Added comments and creation of history ## 01-01-08 (vp) Created (random date...) ## ## TODO or SUGGESTIONS ## ## (v) Check and update if necessary comments of each function!! ## (v) Review the main function and handle all possible crashes. ## COPYRIGHT DISCLAIMER
Vincent Le Guilloux, Peter Schmidtke and Pierre Tuffery, hereby disclaim all copyright interest in the program “fpocket” (which performs protein cavity detection) written by Vincent Le Guilloux and Peter Schmidtke.
Vincent Le Guilloux 28 November 2008 Peter Schmidtke 28 November 2008 Pierre Tuffery 28 November 2008
GNU GPL
This file is part of the fpocket package.
fpocket is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
fpocket is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with fpocket. If not, see <http://www.gnu.org/licenses/>. ## FUNCTION: init_def_dparams
## SPECIFICATION: Initialisation of default parameters.
## PARAMETRES: void
## RETURN: s_dparams*: Pointer to allocated paramers.
Definition at line 76 of file dparams.c.
References s_dparams::f_exp, s_dparams::f_fpcknp, s_dparams::f_fpckp, s_dparams::fcomplex, s_dparams::interface_dist_crit, s_dparams::interface_method, s_dparams::ligs, M_INTERFACE_METHOD1, M_MAX_FILE_NAME_LENGTH, M_OUTPUT_FILE1_DEFAULT, M_OUTPUT_FILE2_DEFAULT, M_OUTPUT_FILE3_DEFAULT, M_VERT_LIG_NEIG_DIST, my_malloc(), and s_dparams::nfiles.
Referenced by get_dpocket_args().
{
        s_dparams *par = (s_dparams*) my_malloc(sizeof(s_dparams)) ;
        par->f_exp = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_fpckp = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_fpcknp = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        strcpy(par->f_exp, M_OUTPUT_FILE1_DEFAULT) ;
        strcpy(par->f_fpckp, M_OUTPUT_FILE2_DEFAULT) ;
        strcpy(par->f_fpcknp, M_OUTPUT_FILE3_DEFAULT) ;
        par->fcomplex = NULL ;
        par->ligs = NULL ;
        par->nfiles = 0 ;
        par->interface_dist_crit = M_VERT_LIG_NEIG_DIST ;
        par->interface_method = M_INTERFACE_METHOD1 ;
        return par ;
}
int parse_dist_crit (char * str, s_dparams * p)
## FUNCTION: parse_dist_crit
## SPECIFICATION: Parsing function for the distance criteria defining the protein-ligand interface.
## PARAMETERS: @ char *str : The string to parse @ s_dparams *p : The structure than will contain the parsed parameter
## RETURN: 0 if the parameter is valid (here a valid integer), 1 if not
Definition at line 356 of file dparams.c.
References s_dparams::interface_dist_crit, M_NO_SIGN, and str_is_float().
Referenced by get_dpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->interface_dist_crit = (float) atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the distance criteria defining the protein-ligand interface.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
void print_dparams (s_dparams * p, FILE * f)
## FUNCTION: print_dparams
## SPECIFICATION: Print function, usefull to debug
## PARAMETRES: @ s_dparams *p : The structure than will contain the parsed parameter @ FILE *f : The file to write in
## RETURN: void
Definition at line 384 of file dparams.c.
References s_dparams::fcomplex, s_dparams::interface_dist_crit, s_dparams::interface_method, s_dparams::ligs, M_INTERFACE_METHOD1, and s_dparams::nfiles.
{
        if(p) {
                fprintf(f, "==============\nParameters of the program: \n");
                int i ;
                for(i = 0 ; i < p->nfiles ; i++) {
                        fprintf(f, "> Protein %d: '%s', '%s'\n", i+1, p->fcomplex[i], p->ligs[i]) ;
                }
                if(p->interface_method == M_INTERFACE_METHOD1)
                        fprintf(f, "> Method used to define explicitely the interface atoms: contacted atom by alpha spheres.\n") ;
                else fprintf(f, "> Method used to define explicitely the interface atoms: ligand's neighbors.\n") ;
                fprintf(f, "> Distance used to define explicitely the interface: %f.\n",
                                        p->interface_dist_crit) ;
                fprintf(f, "==============\n");
        }
        else fprintf(f, "> No parameters detected\n");
}
void print_dpocket_usage (FILE * f)
## FUNCTION: print_dparams_usage
## SPECIFICATION: Displaying usage of the programm in the given buffer
## PARAMETRES: @ FILE *f: buffer to print in
## RETURN:
Definition at line 419 of file dparams.c.
References M_DP_USAGE.
Referenced by get_dpocket_args().
{
        f = (f == NULL) ? stdout:f ;
        fprintf(f, M_DP_USAGE) ;
}