fpocket: fpocket.c File Reference
fpocket.c File Reference
#include "../headers/fpocket.h"
Functions
c_lst_pockets * search_pocket (s_pdb *pdb, s_fparams *params, s_pdb *pdb_w_lig)
Function Documentation
c_lst_pockets* search_pocket (s_pdb * pdb, s_fparams * params, s_pdb * pdb_w_lig)
## FUNCTION: pockets search_pocket
## SPECIFICATION: This function will call all functions needed for the pocket finding algorith and will return the list of pockets found on the protein.
## PARAMETRES: @ s_pdb *pdb : The pdb data of the protein to handle. @ s_fparams : Parameters of the algorithm
## RETURN: A chained list of pockets found, sorted according to the current critera (the default is a scoring function)
Definition at line 82 of file fpocket.c.
References s_fparams::asph_max_size, s_fparams::asph_min_size, clusterPockets(), dropSmallNpolarPockets(), load_vvertices(), M_SCORE_SORT_FUNCT, s_fparams::min_apol_neigh, pck_final_clust(), refinePockets(), reIndexPockets(), set_pockets_descriptors(), sort_pockets(), and c_lst_pockets::vertices.
Referenced by check_fpocket(), desc_pocket(), get_actual_pocket(), mdprocess_pdb(), process_pdb(), and test_set().
{
/*
        clock_t b, e ;
        time_t bt, et ;
*/
        c_lst_pockets *pockets = NULL ;
        /* Calculate and read voronoi vertices comming from qhull */
/*
        fprintf(stdout,"========= fpocket algorithm begins =========\n") ;
        fprintf(stdout, "> Calculating vertices ...\n");
        bt = time(NULL) ;
*/
        s_lst_vvertice *lvert = load_vvertices(pdb, params->min_apol_neigh,
                                                                                                params->asph_min_size,
                                                                                                params->asph_max_size) ;
/*
        et = time(NULL) ;
        fprintf(stdout, "> Vertices successfully calculated in apox. %f sec.\n",
                                        (float) (et-bt)) ;
*/
        if(lvert == NULL) {
                fprintf(stderr, "! Vertice calculation failed!\n");
                return NULL ;
        }
        /* First clustering */
/*              fprintf(stdout,"> Basic clustering ...\n");
                b = clock() ;
*/
        pockets = clusterPockets(lvert, params);
        if(pockets) {
                pockets->vertices = lvert ;
/*
                e = clock() ;
                fprintf(stdout, "> Clustering OK in %f sec.\n",
                                                ((double)e - b) / CLOCKS_PER_SEC) ;
*/
        /* Clustering refinment */
/*
                b = clock() ;
                fprintf(stdout,"> Cluster refinment steps: \n");
*/
                reIndexPockets(pockets) ;
/*
                drop_tiny(pockets) ;
                reIndexPockets(pockets) ;
*/
/*
                fprintf(stdout,"\t* 2nd refinment step -> clustering : based on barycenters...\n");
*/
                refinePockets(pockets, params) ;        /* Refine clustering (rapid) */
                reIndexPockets(pockets) ;
/*
                fprintf(stdout,"\t* 3rd refinment step -> single linkage clusturing...\n");
*/
                pck_final_clust(pockets, params,pdb,pdb_w_lig); /* Single Linkage Clustering */
                reIndexPockets(pockets) ;
        /* Descriptors calculation */
/*
                fprintf(stdout,"> Calculating descriptors and score...\n");
                b = clock() ;
*/
                set_pockets_descriptors(pockets,pdb,params,pdb_w_lig);
/*
                e = clock() ;
                fprintf(stdout, "> Descriptors found in %f sec.\n", ((double)e - b) / CLOCKS_PER_SEC) ;
                fprintf(stdout,"> 4th refinment step -> dropping small and polar pockets...\n");
*/
        /* Drop small and too polar binding pockets */
                dropSmallNpolarPockets(pockets, params);
                reIndexPockets(pockets) ;
/*
                e = clock() ;
                fprintf(stdout, "> Refinment OK in %f sec.\n", ((double)e - b) / CLOCKS_PER_SEC) ;
*/
        /* Sorting pockets */
                sort_pockets(pockets, M_SCORE_SORT_FUNCT) ;
                /*sort_pockets(pockets, M_NASPH_SORT_FUNCT) ;*/
                reIndexPockets(pockets) ;
/*
                fprintf(stdout,"===== fpocket algorithm ends =====\n");
*/
        }
        return pockets ;
}