fpocket: mdparams.h File Reference
mdparams.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <assert.h>
#include "utils.h"
#include "memhandler.h"
#include "fparams.h"
Data Structures
struct s_mdparams
Defines
#define M_MDPAR_INPUT_FILE 'L'
#define M_MDPAR_INPUT_FILE2 'f'
#define M_MDPAR_OUTPUT_FILE 'o'
#define M_MDPAR_SCORING_MODE 'S'
#define M_MDPAR_OUTPUT_ALL_SNAPSHOTS 'a'
#define M_MDP_OUTPUT_FILE1_DEFAULT "mdpout_snapshots_concat.pqr"
#define M_MDP_OUTPUT_FILE2_DEFAULT "mdpout_freq_grid.dx"
#define M_MDP_OUTPUT_FILE3_DEFAULT "mdpout_freq_iso_0_5.pdb"
#define M_MDP_OUTPUT_FILE4_DEFAULT "mdpout_descriptors.txt"
#define M_MDP_OUTPUT_FILE5_DEFAULT "mdpout_mdpocket.pdb"
#define M_MDP_OUTPUT_FILE6_DEFAULT "mdpout_mdpocket_atoms.pdb"
#define M_MDP_OUTPUT_FILE7_DEFAULT "mdpout_all_atom_pdensities.pdb"
#define M_MDP_OUTPUT_FILE8_DEFAULT "mdpout_dens_grid.dx"
#define M_MDP_OUTPUT_FILE9_DEFAULT "mdpout_dens_iso_8.pdb"
#define M_MDP_DEFAULT_ISO_VALUE_FREQ 0.5
#define M_MDP_DEFAULT_ISO_VALUE_DENS 8.0
#define M_MAX_FILE_NAME_LENGTH 300
#define M_NB_MC_ITER 2500
#define M_MDP_USAGE "\***** USAGE (mdpocket) *****\n\\n\1 : Pocket finding on a MD trajectory -> list of pre-aligned pdb ordered by time file:\n\\t./bin/mdpocket -L pdb_list \n\2 : Pocket characterization on a MD trajectory -> list of pre-aligned pdb ordered by \n\ time file and wanted pocket pdb file \n\\t./bin/mdpocket -L pdb_list -f wanted_pocket.pdb \n\\t an example of a wanted pocket file can be obtained by running (1) \n\\t (mdpout_iso_8.pdb) and non wanted grid points should be deleted by hand (i.e. PyMOL).\n\\nOPTIONS (find standard parameters in brackets) \n\n\\t-o (char *) : common prefix of output file (mdpout_snapshots) \n\n\\t-S : if you put this flag, the pocket score is matched to the \n\\t density grid \n\\t-a : output all bfactor colored snapshots\n\n\\t-m (float) : Minimum radius of an alpha-sphere. (3.0)\n\\t-M (float) : Maximum radius of an alpha-sphere. (6.0)\n\\t-A (int) : Minimum number of apolar neighbor for \n\\t an a-sphere to be considered as apolar. (3)\n\\t-i (int) : Minimum number of a-sphere per pocket. (30)\n\\t-D (float) : Maximum distance for first clustering \n\\t algorithm. (1.73)\n\\t-s (float) : Maximum distance for single linkage \n\\t clustering (2.5)\n\\t-n (integer): Minimum number of neighbor close from \n\\t each other (not merged otherwise). (3)\n\\t-r (float) : Maximum distance between two pockets \n\\t barycenter (merged otherwise). (4.5)\n\\t-p (float) : Minimum proportion of apolar sphere in \n\\t a pocket (remove otherwise) (0.0)\n\\t-v (integer): Number of Monte-Carlo iteration for the \n\\t calculation of each pocket volume. (2500)\n\\t-b (integer): Space approximation for the basic method \n\\t of the volume calculation. Not used by \n\\t default (Monte Carlo approximation is) \n\\nSee the manual (man fpocket), or the full documentation for\n\more information.\n\***************************\n"
Functions
s_mdparams * init_def_mdparams (void)
s_mdparams * get_mdpocket_args (int nargs, char **args)
int add_list_snapshots (char *str_list_file, s_mdparams *par)
int add_snapshot (char *snapbuf, s_mdparams *par)
void print_mdparams (s_mdparams *p, FILE *f)
void print_mdpocket_usage (FILE *f)
void free_mdparams (s_mdparams *p)
Define Documentation
#define M_MAX_FILE_NAME_LENGTH 300
Definition at line 73 of file mdparams.h.
#define M_MDP_DEFAULT_ISO_VALUE_DENS 8.0
Definition at line 71 of file mdparams.h.
Referenced by mdpocket_detect().
#define M_MDP_DEFAULT_ISO_VALUE_FREQ 0.5
Definition at line 70 of file mdparams.h.
Referenced by mdpocket_detect().
#define M_MDP_OUTPUT_FILE1_DEFAULT "mdpout_snapshots_concat.pqr"
Definition at line 61 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE2_DEFAULT "mdpout_freq_grid.dx"
Definition at line 62 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE3_DEFAULT "mdpout_freq_iso_0_5.pdb"
Definition at line 63 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE4_DEFAULT "mdpout_descriptors.txt"
Definition at line 64 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE5_DEFAULT "mdpout_mdpocket.pdb"
Definition at line 65 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE6_DEFAULT "mdpout_mdpocket_atoms.pdb"
Definition at line 66 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE7_DEFAULT "mdpout_all_atom_pdensities.pdb"
Definition at line 67 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE8_DEFAULT "mdpout_dens_grid.dx"
Definition at line 68 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_OUTPUT_FILE9_DEFAULT "mdpout_dens_iso_8.pdb"
Definition at line 69 of file mdparams.h.
Referenced by init_def_mdparams().
#define M_MDP_USAGE "\***** USAGE (mdpocket) *****\n\\n\1 : Pocket finding on a MD trajectory -> list of pre-aligned pdb ordered by time file:\n\\t./bin/mdpocket -L pdb_list \n\2 : Pocket characterization on a MD trajectory -> list of pre-aligned pdb ordered by \n\ time file and wanted pocket pdb file \n\\t./bin/mdpocket -L pdb_list -f wanted_pocket.pdb \n\\t an example of a wanted pocket file can be obtained by running (1) \n\\t (mdpout_iso_8.pdb) and non wanted grid points should be deleted by hand (i.e. PyMOL).\n\\nOPTIONS (find standard parameters in brackets) \n\n\\t-o (char *) : common prefix of output file (mdpout_snapshots) \n\n\\t-S : if you put this flag, the pocket score is matched to the \n\\t density grid \n\\t-a : output all bfactor colored snapshots\n\n\\t-m (float) : Minimum radius of an alpha-sphere. (3.0)\n\\t-M (float) : Maximum radius of an alpha-sphere. (6.0)\n\\t-A (int) : Minimum number of apolar neighbor for \n\\t an a-sphere to be considered as apolar. (3)\n\\t-i (int) : Minimum number of a-sphere per pocket. (30)\n\\t-D (float) : Maximum distance for first clustering \n\\t algorithm. (1.73)\n\\t-s (float) : Maximum distance for single linkage \n\\t clustering (2.5)\n\\t-n (integer): Minimum number of neighbor close from \n\\t each other (not merged otherwise). (3)\n\\t-r (float) : Maximum distance between two pockets \n\\t barycenter (merged otherwise). (4.5)\n\\t-p (float) : Minimum proportion of apolar sphere in \n\\t a pocket (remove otherwise) (0.0)\n\\t-v (integer): Number of Monte-Carlo iteration for the \n\\t calculation of each pocket volume. (2500)\n\\t-b (integer): Space approximation for the basic method \n\\t of the volume calculation. Not used by \n\\t default (Monte Carlo approximation is) \n\\nSee the manual (man fpocket), or the full documentation for\n\more information.\n\***************************\n"
the usage print content
Definition at line 79 of file mdparams.h.
Referenced by print_mdpocket_usage().
#define M_MDPAR_INPUT_FILE 'L'
COPYRIGHT DISCLAIMER
Vincent Le Guilloux, Peter Schmidtke and Pierre Tuffery, hereby disclaim all copyright interest in the program “fpocket” (which performs protein cavity detection) written by Vincent Le Guilloux and Peter Schmidtke.
Vincent Le Guilloux 28 November 2008 Peter Schmidtke 28 November 2008 Pierre Tuffery 28 November 2008
GNU GPL
This file is part of the fpocket package.
fpocket is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
fpocket is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with fpocket. If not, see <http://www.gnu.org/licenses/>.
Definition at line 54 of file mdparams.h.
Referenced by get_mdpocket_args().
#define M_MDPAR_INPUT_FILE2 'f'
Definition at line 55 of file mdparams.h.
Referenced by get_mdpocket_args().
#define M_MDPAR_OUTPUT_ALL_SNAPSHOTS 'a'
Definition at line 58 of file mdparams.h.
Referenced by get_mdpocket_args().
#define M_MDPAR_OUTPUT_FILE 'o'
Definition at line 56 of file mdparams.h.
Referenced by get_mdpocket_args().
#define M_MDPAR_SCORING_MODE 'S'
Definition at line 57 of file mdparams.h.
Referenced by get_mdpocket_args().
#define M_NB_MC_ITER 2500
Definition at line 74 of file mdparams.h.
Function Documentation
int add_list_snapshots (char * str_list_file, s_mdparams * par)
## FUNCTION: add_list_snapshots
## SPECIFICATION: Load a list of snapshot pdb file path. This file should have the following format:
snapshot_pdb_file snapshot_pdb_file2 snapshot_pdb_file3 (...)
Each snapshot file will be stored in the parameters structure.
## PARAMETRES: @ char *str_list_file : Path of the file containing all data @ s_mdparams *par : Structures that stores all thoses files
## RETURN: int: Number of file read.
Definition at line 244 of file mdparams.c.
References add_snapshot(), M_MAX_PDB_NAME_LEN, and s_mdparams::nfiles.
Referenced by get_mdpocket_args().
{
        FILE *f;
        int n,
                nread = 0,
                status ;
        char buf[M_MAX_PDB_NAME_LEN*2 + 6],
                 snapbuf[M_MAX_PDB_NAME_LEN];
        /* Loading data. */
        f = fopen(str_list_file, "r") ;
/*
        printf(str_list_file);
*/
        if(f) {
                while(fgets(buf, 210, f)) {
/*
                        printf("B: %s\n" , buf);
*/
                        n = par->nfiles ;
                        status = sscanf(buf, "%s", snapbuf) ;
                        if(status < 1) {
                                fprintf(stderr, "! Skipping row '%s' with bad format (status %d).\n",
                                                                buf, status) ;
                        }
                        else {
                                nread += add_snapshot(snapbuf, par) ;
                        }
                }
        }
        else {
                fprintf(stderr, "! File %s doesn't exists\n", str_list_file) ;
        }
        fclose(f);
        return nread ;
}
int add_snapshot (char * snapbuf, s_mdparams * par)
## FUNCTION: add_snapshot
## SPECIFICATION: Add a set of data to the list of set of data in the parameters. this function is used for the mdpocket program only.
The function will try to open the file, and data will be stored only if the file exists, and if the name of the ligand is valid.
## PARAMETERS: @ char *snapbuf : The snapshots path @ s_mdparams *par: The structure than contains parameters.
## RETURN: int: 1 if everything is OK, 0 if not.
Definition at line 303 of file mdparams.c.
References fopen_pdb_check_case(), s_mdparams::fsnapshot, my_malloc(), my_realloc(), and s_mdparams::nfiles.
Referenced by add_list_snapshots().
{
        int nm1 ;
        FILE *f = fopen_pdb_check_case(snapbuf, "r") ;
        if(f) {
                nm1 = par->nfiles ;
                par->nfiles += 1 ;
                par->fsnapshot = (char**) my_realloc(par->fsnapshot, (par->nfiles)*sizeof(char*)) ;
                par->fsnapshot[nm1] = (char *)my_malloc((strlen(snapbuf)+1)*sizeof(char)) ;
                strcpy(par->fsnapshot[nm1], snapbuf) ;
                fclose(f) ;
        }
        else {
                fprintf(stdout, "! The pdb file '%s' doesn't exists.\n", snapbuf) ;
                return 0 ;
        }
        return 1 ;
}
void free_mdparams (s_mdparams * p)
## FUNCTION: free_params
## SPECIFICATION: Free parameters
## PARAMETRES: @ s_mdparams *p: Pointer to the structure to free
## RETURN: void
Definition at line 397 of file mdparams.c.
References s_mdparams::f_densdx, s_mdparams::f_desc, s_mdparams::f_freqdx, s_mdparams::f_pqr, s_mdparams::fpar, free_fparams(), s_mdparams::fsnapshot, and my_free().
Referenced by get_mdpocket_args(), and main().
{
        if(p) {
                if(p->fsnapshot) {
                        my_free(p->fsnapshot);
                        p->fsnapshot = NULL;
                }
                if(p->f_pqr) {
                        my_free(p->f_pqr);
                        p->f_pqr = NULL;
                }
                if(p->f_densdx) {
                        my_free(p->f_densdx);
                        p->f_densdx = NULL ;
                }
                if(p->f_freqdx) {
                        my_free(p->f_freqdx);
                        p->f_freqdx = NULL ;
                }
                if(p->f_desc) {
                        my_free(p->f_desc);
                        p->f_desc = NULL;
                }
                free_fparams(p->fpar);
                my_free(p) ;
        }
}
s_mdparams* get_mdpocket_args (int nargs, char ** args)
## FUNCTION: get_dpocket_args
## SPECIFICATION: This function analyse the user's command line and parse it to store parameters for the descriptor calculator programm.
## PARAMETRES: @ int nargs : Number of arguments @ char **args : Arguments of main program
## RETURN: s_mdparams*: Pointer to parameters
Definition at line 123 of file mdparams.c.
References add_list_snapshots(), s_mdparams::bfact_on_all, s_mdparams::f_apdb, s_mdparams::f_appdb, s_mdparams::f_densdx, s_mdparams::f_densiso, s_mdparams::f_desc, s_mdparams::f_freqdx, s_mdparams::f_freqiso, s_mdparams::f_ppdb, s_mdparams::f_pqr, s_mdparams::flag_scoring, s_mdparams::fpar, free_mdparams(), s_mdparams::fwantedpocket, get_fpocket_args(), init_def_mdparams(), is_fpocket_opt(), M_MAX_FILE_NAME_LENGTH, M_MDPAR_INPUT_FILE, M_MDPAR_INPUT_FILE2, M_MDPAR_OUTPUT_ALL_SNAPSHOTS, M_MDPAR_OUTPUT_FILE, M_MDPAR_SCORING_MODE, print_mdpocket_usage(), and remove_ext().
Referenced by main().
{
        int i,
                status = 0,
                nstats = 0,
                npdb=0;
        char *str_list_file = NULL ;
        s_mdparams *par = init_def_mdparams() ;
        par->fpar = get_fpocket_args(nargs, args) ;
        /* Read arguments by flags */
        for (i = 1; i < nargs; i++) {
                if (strlen(args[i]) == 2 && args[i][0] == '-') {
                        switch (args[i][1]) {
                                case M_MDPAR_OUTPUT_FILE :
                                                if(nstats >= 1) fprintf(stdout, "! More than one single file for the stats output file has been given. Ignoring this one.\n") ;
                                                else {
                                                        if(i < nargs-1) {
                                                                if(strlen(args[++i]) < M_MAX_FILE_NAME_LENGTH) {
                                                                        remove_ext(args[i]) ;
                                                                        sprintf(par->f_pqr, "%s.pqr", args[i]) ;
                                                                        sprintf(par->f_freqdx, "%s.dx", args[i]) ;
                                                                        sprintf(par->f_densdx, "%s.dx", args[i]) ;
                                                                        sprintf(par->f_freqiso, "%s_freq_iso_0_5.pdb", args[i]) ;
                                                                        sprintf(par->f_densiso, "%s_dens_iso_8.pdb", args[i]) ;
                                                                        sprintf(par->f_desc, "%s_descriptors.txt", args[i]) ;
                                                                        sprintf(par->f_ppdb, "%s_mdpocket.pdb", args[i]) ;
                                                                        sprintf(par->f_apdb, "%s_mdpocket_atoms.pdb", args[i]) ;
                                                                        sprintf(par->f_appdb, "%s_all_atom_pdensities.pdb", args[i]) ;
                                                                }
                                                                else fprintf(stdout, "! Output file name is too long... Keeping default.") ;
                                                        }
                                                        else {
                                                                fprintf(stdout, "! Invalid output file name argument missing.\n") ;
                                                                status += 1 ;
                                                        }
                                                }
                                                break ;
                                case M_MDPAR_INPUT_FILE :
                                                if(i < nargs-1) str_list_file = args[++i] ;
                                                else {
                                                        fprintf(stdout, "! Input file name argument missing.\n") ;
                                                        status += 1 ;
                                                }
                                                 break ;
                                case M_MDPAR_INPUT_FILE2 :
                                                if(npdb >= 1) fprintf(stderr,
                                                        "! Only first input pdb will be used.\n") ;
                                                else {
                                                        strcpy(par->fwantedpocket, args[++i]) ; npdb++ ;
                                                }
                                                break ;
                                case M_MDPAR_SCORING_MODE :
                                                par->flag_scoring=1;
                                                break;
                                case M_MDPAR_OUTPUT_ALL_SNAPSHOTS :
                                                par->bfact_on_all=1;
                                                break;
                                default:
                                        //  Check fpocket parameters!
                                        if(!is_fpocket_opt(args[i][1])) {
                                                fprintf(stdout, "> Unknown option '%s'. Ignoring it.\n",
                                                                args[i]) ;
                                        }
                                        break ;
                        }
                }
        }
        if(status > 0) {
                free_mdparams(par) ;
                par = NULL ;
                print_mdpocket_usage(stdout);
        }
        else {
                if(str_list_file) {
                        int res = add_list_snapshots(str_list_file, par) ;
                        if(res <= 0) {
                                fprintf(stdout, "! No data has been read.\n") ;
                                free_mdparams(par) ;
                                par = NULL ;
                                print_mdpocket_usage(stdout);
                        }
                }
                else {
                        fprintf(stdout, "! No input file given... Try again :).\n") ;
                        free_mdparams(par) ;
                        par = NULL ;
                        print_mdpocket_usage(stdout);
                }
        }
        return par;
}
s_mdparams* init_def_mdparams (void)
## GENERAL INFORMATION ## ## FILE mdparams.c ## AUTHORS P. Schmidtke and V. Le Guilloux ## LAST MODIFIED 28-11-08 ## ## SPECIFICATIONS ## ## Handle parameters (parse the command line and sore values) ## for the mdpocket programm. ## ## MODIFICATIONS HISTORY ## ## 28-11-08 (v) Comments UTD + relooking ## 27-11-08 (v) Minor Relooking ## 01-04-08 (v) Added comments and creation of history ## 01-01-08 (vp) Created (random date...) ## ## TODO or SUGGESTIONS ## ## (v) Check and update if necessary comments of each function!! ## (v) Review the main function and handle all possible crashes. ## COPYRIGHT DISCLAIMER
Vincent Le Guilloux, Peter Schmidtke and Pierre Tuffery, hereby disclaim all copyright interest in the program “fpocket” (which performs protein cavity detection) written by Vincent Le Guilloux and Peter Schmidtke.
Vincent Le Guilloux 28 November 2008 Peter Schmidtke 28 November 2008 Pierre Tuffery 28 November 2008
GNU GPL
This file is part of the fpocket package.
fpocket is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
fpocket is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with fpocket. If not, see <http://www.gnu.org/licenses/>. ## FUNCTION: init_def_mdparams
## SPECIFICATION: Initialisation of default parameters.
## PARAMETRES: void
## RETURN: s_mdparams*: Pointer to allocated paramers.
Definition at line 76 of file mdparams.c.
References s_mdparams::bfact_on_all, s_mdparams::f_apdb, s_mdparams::f_appdb, s_mdparams::f_densdx, s_mdparams::f_densiso, s_mdparams::f_desc, s_mdparams::f_freqdx, s_mdparams::f_freqiso, s_mdparams::f_ppdb, s_mdparams::f_pqr, s_mdparams::flag_scoring, s_mdparams::fsnapshot, s_mdparams::fwantedpocket, M_MAX_FILE_NAME_LENGTH, M_MDP_OUTPUT_FILE1_DEFAULT, M_MDP_OUTPUT_FILE2_DEFAULT, M_MDP_OUTPUT_FILE3_DEFAULT, M_MDP_OUTPUT_FILE4_DEFAULT, M_MDP_OUTPUT_FILE5_DEFAULT, M_MDP_OUTPUT_FILE6_DEFAULT, M_MDP_OUTPUT_FILE7_DEFAULT, M_MDP_OUTPUT_FILE8_DEFAULT, M_MDP_OUTPUT_FILE9_DEFAULT, my_malloc(), and s_mdparams::nfiles.
Referenced by get_mdpocket_args().
{
        s_mdparams *par = (s_mdparams*) my_malloc(sizeof(s_mdparams)) ;
        par->f_pqr = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_freqdx = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_densdx = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_freqiso = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_densiso = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_desc = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_ppdb = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_apdb = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char)) ;
        par->f_appdb = (char *)my_malloc(M_MAX_FILE_NAME_LENGTH*sizeof(char));
        strcpy(par->f_pqr, M_MDP_OUTPUT_FILE1_DEFAULT) ;
        strcpy(par->f_freqdx, M_MDP_OUTPUT_FILE2_DEFAULT) ;
        strcpy(par->f_freqiso, M_MDP_OUTPUT_FILE3_DEFAULT) ;
        strcpy(par->f_desc, M_MDP_OUTPUT_FILE4_DEFAULT) ;
        strcpy(par->f_ppdb, M_MDP_OUTPUT_FILE5_DEFAULT) ;
        strcpy(par->f_apdb, M_MDP_OUTPUT_FILE6_DEFAULT) ;
        strcpy(par->f_appdb, M_MDP_OUTPUT_FILE7_DEFAULT);
        strcpy(par->f_densdx, M_MDP_OUTPUT_FILE8_DEFAULT) ;
        strcpy(par->f_densiso, M_MDP_OUTPUT_FILE9_DEFAULT) ;
        par->fsnapshot = NULL ;
        par->fwantedpocket[0] = 0 ;
        par->nfiles = 0 ;
        par->flag_scoring=0;
        par->bfact_on_all=0;
        return par ;
}
void print_mdparams (s_mdparams * p, FILE * f)
## FUNCTION: print_mdparams
## SPECIFICATION: Print function, usefull to debug
## PARAMETRES: @ s_mdparams *p : The structure than will contain the parsed parameter @ FILE *f : The file to write in
## RETURN: void
Definition at line 345 of file mdparams.c.
References s_mdparams::fsnapshot, s_mdparams::fwantedpocket, and s_mdparams::nfiles.
Referenced by main().
{
        if(p) {
                fprintf(f, "==============\nParameters of the program: \n");
                int i ;
                for(i = 0 ; i < p->nfiles ; i++) {
                        fprintf(f, "> Snaphot %d: '%s'\n", i+1, p->fsnapshot[i]) ;
                }
                fprintf(f, "==============\n");
                if(p->fwantedpocket[0]!=0){
                    fprintf(f,"Wanted pocket given in file : %s\n",p->fwantedpocket);
                    fprintf(f, "==============\n");
                }
        }
        else fprintf(f, "> No parameters detected\n");
}
void print_mdpocket_usage (FILE * f)
## FUNCTION: print_mdparams_usage
## SPECIFICATION: Displaying usage of the programm in the given buffer
## PARAMETRES: @ FILE *f: buffer to print in
## RETURN:
Definition at line 376 of file mdparams.c.
References M_MDP_USAGE.
Referenced by get_mdpocket_args().
{
        f = (f == NULL) ? stdout:f ;
        fprintf(f, M_MDP_USAGE) ;
}