fpocket: mdpmain.c File Reference
mdpmain.c File Reference
#include "../headers/mdpmain.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
## FUNCTION: int main(int argc, char *argv[])
## SPECIFICATION: Main program for dpocket!
Definition at line 68 of file mdpmain.c.
References free_all(), free_mdparams(), s_mdparams::fwantedpocket, get_mdpocket_args(), mdpocket_characterize(), mdpocket_detect(), and print_mdparams().
{
    s_mdparams *par = get_mdpocket_args(argc, argv) ;
    print_mdparams(par, stdout) ;
    if(par && par->fwantedpocket[0]==0) mdpocket_detect(par) ; /* run only pocket detection, 1st way of running mdpocket*/
    else if(par) mdpocket_characterize(par);                    /* run pocket characterization 2nd way of running mdpocket*/
    free_mdparams(par) ;
    free_all() ;
    return 0 ;
}