fpocket: mdpmem.c File Reference
mdpmem.c File Reference
#include "../headers/mdpmem.h"
Functions
s_mdconcat * init_md_concat (void)
void alloc_first_md_concat (s_mdconcat *m, size_t n)
void realloc_md_concat (s_mdconcat *m, size_t n)
void free_mdconcat (s_mdconcat *m)
Function Documentation
void alloc_first_md_concat (s_mdconcat * m, size_t n)
## FUNCTION: alloc_first_md_concat
## SPECIFICATION: Allocate memory for the md concat structure (first snapshot)
## PARAMETRES: @ s_mdconcat *m: Pointer to the structure to free, @ size_t n: Number of vertices in the snapshot to add to m
## RETURN: void
Definition at line 115 of file mdpmem.c.
References my_malloc(), s_mdconcat::n_vertpos, and s_mdconcat::vertpos.
{
    size_t z;
    m->vertpos=(float **) my_malloc(sizeof(float *)*n);
    for(z=0;z<n;z++){
        m->vertpos[z]=(float *)my_malloc(sizeof(float)*4);
        m->vertpos[z][0]=0.0;
        m->vertpos[z][1]=0.0;
        m->vertpos[z][2]=0.0;
        m->vertpos[z][3]=0.0;
    }
    m->n_vertpos=n;
}
void free_mdconcat (s_mdconcat * m)
## FUNCTION: free_mdconcat
## SPECIFICATION: Free the mdconcat structure
## PARAMETRES: @ s_mdconcat *m: Pointer to the structure to free
## RETURN: void
Definition at line 170 of file mdpmem.c.
References my_free(), s_mdconcat::n_vertpos, and s_mdconcat::vertpos.
{
    size_t i;
    for(i=0;i<m->n_vertpos;i++){
        my_free(m->vertpos[i]);
    }
    my_free(m->vertpos);
    my_free(m);
}
s_mdconcat* init_md_concat (void)
## FUNCTION: init_md_concat
## SPECIFICATION: Allocate memory for the concatenated voronoi vertice structure Currently NOT USED
## PARAMETRES: void
## RETURN: s_mdconcat * : Structure containing allocated memory
Definition at line 90 of file mdpmem.c.
References my_malloc(), s_mdconcat::n_snapshots, s_mdconcat::n_vertpos, and s_mdconcat::vertpos.
{
    s_mdconcat *m=(s_mdconcat *) my_malloc(sizeof(s_mdconcat));
    m->n_vertpos=0;
    m->vertpos=NULL;
    m->n_snapshots=0;
    return m;
}
void realloc_md_concat (s_mdconcat * m, size_t n)
## FUNCTION: realloc_md_concat
## SPECIFICATION: Reallocate memory for the md concat structure (to add a new snapshot)
## PARAMETRES: @ s_mdconcat *m: Pointer to the structure to free, @ size_t n: Number of vertices in the snapshot to add to m
## RETURN: void
Definition at line 143 of file mdpmem.c.
References my_malloc(), my_realloc(), s_mdconcat::n_vertpos, and s_mdconcat::vertpos.
{
    size_t z;
    m->vertpos=(float **) my_realloc(m->vertpos,sizeof(float *)*(m->n_vertpos+n));
    for(z=0;z<n;z++){
        m->vertpos[m->n_vertpos+z]=(float *)my_malloc(sizeof(float)*4);
        m->vertpos[m->n_vertpos+z][0]=0.0;
        m->vertpos[m->n_vertpos+z][1]=0.0;
        m->vertpos[m->n_vertpos+z][2]=0.0;
        m->vertpos[m->n_vertpos+z][3]=0.0;
    }
    m->n_vertpos+=n;
}