fpocket: memhandler.c File Reference
memhandler.c File Reference
#include "../headers/memhandler.h"
Data Structures
struct ptr_node
struct ptr_lst
Functions
static ptr_node * ptr_node_alloc (void *ptr)
static void add_bloc (void *bloc)
static void remove_bloc (void *bloc)
void * my_malloc (size_t s)
void * my_calloc (size_t nb, size_t s)
void * my_realloc (void *ptr, size_t s)
void my_free (void *bloc)
int get_number_of_objects_in_memory (void)
void print_number_of_objects_in_memory (void)
void free_all (void)
void my_exit (void)
void print_ptr_lst (void)
Variables
static ptr_lst * ST_lst_alloc = NULL
Function Documentation
static void add_bloc (void * bloc) [static]
## FUNCTION: static add_bloc
## SPECIFICATION: Add an allocated pointer (bloc) to the list ST_lst_alloc.
This function is supposed to be called by my_malloc, my_calloc or my_realloc functions only.
## PARAMETRES: @ void *bloc: The pointer to remove
## RETURN:
Definition at line 289 of file memhandler.c.
References ptr_lst::first, ptr_lst::last, my_exit(), ptr_lst::n_ptr, ptr_node::next, and ptr_node_alloc().
Referenced by my_calloc(), my_malloc(), and my_realloc().
{
        #ifdef M_MEM_DEBUG
                if(ST_fdebug) fprintf(ST_fdebug, "> Adding bloc %p\n", bloc) ;
        #endif
        /* First check if the list exists, if not create it. */
        if(!ST_lst_alloc) {
                ST_lst_alloc = (ptr_lst*) malloc(sizeof(ptr_lst)) ;
                if(!ST_lst_alloc) {
                        fprintf(stderr, "! malloc failed in add_bloc while creating the list. Programm will exit.\n") ;
                        my_exit() ;
                }
                #ifdef M_MEM_DEBUG
                        ST_fdebug = fopen("memory_debug.tmp", "w") ;
                #endif
                ST_lst_alloc->first = NULL ;
                ST_lst_alloc->last = NULL ;
                ST_lst_alloc->n_ptr = 0 ;
        }
        /* Now add the bloc to the chained list */
        ptr_node *newn = ptr_node_alloc(bloc) ;
        if(ST_lst_alloc->first) {
                newn->next = ST_lst_alloc->first ;
                ST_lst_alloc->first = newn ;
        }
        else {
                ST_lst_alloc->first = newn ;
                ST_lst_alloc->last = newn ;
        }
        ST_lst_alloc->n_ptr += 1 ;
}
void free_all (void)
## FUNCTION: free_all
## SPECIFICATION: Free all pointers allocated and present in the list ST_lst_alloc. If a NULL pointer is found, ignore it.
## PARAMETRES: void
## RETURN: void
Definition at line 427 of file memhandler.c.
References ptr_lst::first, ptr_node::next, and ptr_node::ptr.
Referenced by main(), and my_exit().
{
        if(ST_lst_alloc) {
                ptr_node *cur = ST_lst_alloc->first,
                                 *tmp = cur ;
                while(cur) {
                        if(cur->ptr) {
                        #ifdef M_MEM_DEBUG
                                if(ST_fdebug) fprintf(ST_fdebug, "> Freeing <%p>.\n", cur->ptr) ;
                        #endif
                                free(cur->ptr) ;
                                cur->ptr = NULL ;
                        }
                #ifdef M_MEM_DEBUG
                        else {
                                if(ST_fdebug) fprintf(ST_fdebug, "! A NULL bloc has been found in free_all!! Ignoring this bloc...\n") ;
                        }
                #endif
                        tmp = cur->next ;
                        cur->next = NULL ;
                        free(cur) ;
                        cur = tmp ;
                }
                free(ST_lst_alloc) ;
                ST_lst_alloc = NULL ;
        }
#ifdef M_MEM_DEBUG
        else {
                if(ST_fdebug) fprintf(ST_fdebug, "! No bloc allocated -> cannot free memory...\n") ;
        }
#endif
}
int get_number_of_objects_in_memory (void)
Definition at line 401 of file memhandler.c.
References ptr_lst::n_ptr.
{
    if(ST_lst_alloc) {
        return(ST_lst_alloc->n_ptr);
    }
    return(0);
}
void* my_calloc (size_t nb, size_t s)
## FUNCTION: my_calloc
## SPECIFICATION: Allocate memory for nb bloc of size s using calloc standart function.
## PARAMETRES: @ size_t nb : Number of bloc to allocate @ size_t s : Size of the bloc to allocate
## RETURN: void *: Pointer to the allocated bloc
Definition at line 153 of file memhandler.c.
References add_bloc(), and my_exit().
Referenced by fill_vvertices(), get_pocket_pvertices(), rpdb_open(), sort_pockets(), str_split(), and test_pdb_line().
{
        void *bloc = calloc(nb, s) ;
        if(bloc == NULL){
                fprintf(stderr, "! malloc failed in my_bloc_malloc. Programm will exit, as demanded.\n") ;
                my_exit() ;
        }
        #ifdef M_MEM_DEBUG
        if(ST_fdebug) fprintf(ST_fdebug, "> (C)Allocation success at: <%p>\n", bloc) ;
        #endif
        add_bloc(bloc) ;
        return bloc ;
}
void my_exit (void)
## FUNCTION: my_exit
## SPECIFICATION: Before exiting the programm, just free all allocated pointers (if any). This allows to exit the programme whenever one wants during the execution without dealing with memory allocation/desallocation.
This implies to use my_malloc and my_free functions instead of standart functions. Only memory blocs allocated with those functions will be freed when my_exit is called.
## PARAMETRES: void
## RETURN: void
Definition at line 483 of file memhandler.c.
References free_all().
Referenced by add_bloc(), my_calloc(), my_malloc(), my_realloc(), and ptr_node_alloc().
{
        free_all() ;
        exit(1) ;
}
void my_free (void * bloc)
## FUNCTION: my_free
## SPECIFICATION: Free memory for the given bloc, and remove this pointer from the list.
## PARAMETRES: @ void *bloc: Pointer to free.
## RETURN:
Definition at line 255 of file memhandler.c.
References remove_bloc().
Referenced by c_lst_pocket_free(), c_lst_vertices_free(), check_fparams(), check_fpocket(), check_pockets(), clusterPockets(), desc_pocket(), dropPocket(), f_readl(), free_dparams(), free_fparams(), free_mdconcat(), free_mdparams(), free_pdb_atoms(), free_s_vsort(), free_tab_str(), free_tparams(), free_vert_lst(), get_actual_pocket_DEPRECATED(), get_explicit_desc(), init_md_grid(), load_vvertices(), mdpocket_characterize(), mergePockets(), rpdb_open(), set_pockets_descriptors(), sort_pockets(), test_pdb_line(), test_set(), write_pocket_pdb(), and write_pocket_pdb_DB().
{
        if(bloc) {
        #ifdef M_MEM_DEBUG
                if(ST_fdebug) fprintf(ST_fdebug, "> (my_free) Freeing bloc <%p>!\n", bloc) ;
                fflush(ST_fdebug) ;
        #endif
                remove_bloc(bloc) ;
                free(bloc) ;
        }
        else {
        #ifdef M_MEM_DEBUG
                if(ST_fdebug) fprintf(ST_fdebug, "! Cannot free a NULL variable!\n") ;
        #endif
        }
}
void* my_malloc (size_t s)
## FUNCTION: my_malloc
## SPECIFICATION: Allocate memory for a bloc of size s.
## PARAMETRES: @ size_t s : Size of the bloc to allocate
## RETURN: void *: Pointer to the allocated bloc
Definition at line 121 of file memhandler.c.
References add_bloc(), and my_exit().
Referenced by add_complexe(), add_prot(), add_snapshot(), alloc_first_md_concat(), alloc_pocket(), allocate_s_desc(), c_lst_pockets_alloc(), c_lst_vertices_alloc(), check_fparams(), check_fpocket(), f_readl(), fill_vvertices(), float_get_min_max_from_pockets(), get_fpocket_args(), get_mol_atm_neigh(), get_mol_ctd_atm_neigh(), get_mol_vert_neigh(), get_pocket_contacted_atms(), get_sorted_list(), get_vert_contacted_atms(), get_wanted_atom_ids(), init_def_dparams(), init_def_fparams(), init_def_mdparams(), init_def_tparams(), init_md_concat(), init_md_grid(), load_vvertices(), mdpocket_characterize(), node_pocket_alloc(), node_vertice_alloc(), pck_final_clust(), realloc_md_concat(), rpdb_open(), set_ASA(), set_pockets_descriptors(), write_pocket_pdb(), and write_pocket_pdb_DB().
{
        void *bloc = malloc(s) ;
        if(bloc == NULL) {
                fprintf(stderr, "! malloc failed in my_bloc_malloc. Programm will exit, as demanded.\n") ;
                my_exit() ;
        }
        #ifdef M_MEM_DEBUG
        if(ST_fdebug) fprintf(ST_fdebug, "> (M)Allocation success at: <%p>\n", bloc) ;
        #endif
        add_bloc(bloc) ;
        return bloc ;
}
void* my_realloc (void * ptr, size_t s)
## FUNCTION: my_realloc
## SPECIFICATION: Allocate memory for a bloc of size s using calloc standart function.
## PARAMETRES: @ size_t s : Size of the bloc to allocate @ int exit : Whether we exit the programm if malloc fails.
## RETURN: void *: Pointer to the allocated bloc
Definition at line 184 of file memhandler.c.
References add_bloc(), my_exit(), and remove_bloc().
Referenced by add_complexe(), add_prot(), add_snapshot(), get_mol_atm_neigh(), get_mol_ctd_atm_neigh(), get_mol_vert_neigh(), get_pocket_contacted_atms(), get_wanted_atom_ids(), load_vvertices(), realloc_md_concat(), and write_pocket_pdb().
{
        void *tmp = ptr ;
        ptr = realloc(ptr, s) ;
        if(ptr == NULL){
                fprintf(stderr, "! malloc failed in my_bloc_malloc. Programm will exit, as demanded.\n") ;
                my_exit() ;
        }
        else {
                if(tmp && tmp != ptr) {
                #ifdef M_MEM_DEBUG
                         if(ST_fdebug) fprintf(ST_fdebug, "> Realloc generates a new pointer: <%p> newly allocated at %p. \n", tmp, ptr) ;
                #endif
        /* If the newly allocated pointer is different from previou s
           one, remove previous from the list and add new one. Else,
           ptr doesn't need to be added. */
                        remove_bloc(tmp) ;
                        add_bloc(ptr) ;
                }
        }
        return ptr ;
}
void print_number_of_objects_in_memory (void)
Definition at line 408 of file memhandler.c.
References ptr_lst::n_ptr.
{
    if(ST_lst_alloc) {
        printf("\nHaving %d objects in memory\n",ST_lst_alloc->n_ptr);
    }
}
void print_ptr_lst (void)
## FUNCTION: print_ptr_lst
## SPECIFICATION: Print allocated pointers stored in ST_lst_alloc for debugging purpose.
## PARAMETRES: void
## RETURN: void
Definition at line 502 of file memhandler.c.
References ptr_lst::first, ptr_lst::last, ptr_lst::n_ptr, ptr_node::next, and ptr_node::ptr.
{
        if(ST_lst_alloc && ST_lst_alloc->n_ptr > 0) {
                int i = 0 ;
                ptr_node *cur = ST_lst_alloc->first ;
                fprintf(stdout, "\t==============\n\tLst of %d allocated ptr: \n", (int) ST_lst_alloc->n_ptr) ;
                fprintf(stdout, "\tFirst: <%p> - Last: <%p>\n", ST_lst_alloc->first->ptr, ST_lst_alloc->last->ptr) ;
                while(cur) {
                        if(cur->ptr) {
                                fprintf(stdout, "\t<%p> <%d>\n", cur->ptr, (int)sizeof(cur->ptr)) ;
                        }
                        else {
                                fprintf(stdout, "\t! A NULL bloc has been found in position %d.\n", i) ;
                        }
                        cur = cur->next ;
                }
        }
        else {
                fprintf(stdout, "\t! No bloc allocated yet...\n") ;
        }
}
static ptr_node * ptr_node_alloc (void * ptr) [static]
## FONCTION: ptr_node_alloc
## SPECIFICATION: Allocate a simple chained node.
## PARAMETRES: @ void *ptr: Pointer
## RETURN: ptr_node*
Definition at line 225 of file memhandler.c.
References my_exit(), ptr_node::next, and ptr_node::ptr.
Referenced by add_bloc().
{
        ptr_node *node = (ptr_node *) malloc(sizeof(ptr_node)) ;
        if(node) {
                node->ptr = ptr ;
                node->next = NULL ;
        }
        else {
                fprintf(stderr, "! malloc failed in my_bloc_malloc. Programm will exit, as demanded.\n") ;
                my_exit() ;
        }
        return node ;
}
static void remove_bloc (void * bloc) [static]
## FUNCTION: static remove_bloc
## SPECIFICATION: Remove the given pointer (node) from the list ST_lst_alloc. Donc free the memory.
This function is supposed to be called by my_free function and not another.
## PARAMETRES: @ void *bloc: The pointer to remove.
## RETURN: void
Definition at line 343 of file memhandler.c.
References ptr_lst::first, ptr_lst::last, ptr_lst::n_ptr, ptr_node::next, and ptr_node::ptr.
Referenced by my_free(), and my_realloc().
{
#ifdef M_MEM_DEBUG
        size_t i = 0 ;
#endif
        /* First check if the list exists, if not create it. */
        if(ST_lst_alloc) {
                ptr_node *cur = ST_lst_alloc->first,
                                 *prev = cur ;
        #ifdef M_MEM_DEBUG
                if(!cur && ST_fdebug) fprintf(ST_fdebug, "> No element in the list, so cannot remove <%p>...\n", bloc) ;
                size_t prev_s = ST_lst_alloc->n_ptr ;
        #endif
                while(cur) {
                        if(cur->ptr == bloc) {
                        /* Remove bloc */
                                #ifdef M_MEM_DEBUG
                                        if(ST_fdebug) fprintf(ST_fdebug, "> Removing <%p>...\n", cur->ptr) ;
                                #endif
                                if(cur == ST_lst_alloc->first) {
                                        ST_lst_alloc->first = cur->next ;
                                }
                                else if(cur == ST_lst_alloc->last) {
                                        ST_lst_alloc->last = prev ;
                                        prev->next = NULL ;
                                }
                                else {
                                        prev->next = cur->next ;
                                }
                                cur->next = NULL ;
                                free(cur) ;
                                ST_lst_alloc->n_ptr -= 1 ;
                                break ;
                        }
                #ifdef M_MEM_DEBUG
                        i++ ;
                #endif
                        prev = cur ;
                        cur = cur->next ;
                }
        #ifdef M_MEM_DEBUG
                if(i == prev_s && ST_fdebug) fprintf(ST_fdebug, "Memhandler: <%p> not found!\n", bloc) ;
        #endif
        }
        #ifdef M_MEM_DEBUG
        else {
                if(ST_fdebug) fprintf(ST_fdebug, "! No bloc allocated -> cannot remove given argument from an empty list.\n") ;
        }
        #endif
}
Variable Documentation
ptr_lst* ST_lst_alloc = NULL [static]
Definition at line 97 of file memhandler.c.