fpocket: pertable.h File Reference
pertable.h File Reference
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include "utils.h"
Functions
float pte_get_vdw_ray (const char *symbol)
float pte_get_mass (const char *symbol)
float pte_get_enegativity (const char *symbol)
int is_valid_element (const char *str, int ignore_case)
int element_in_std_res (char *res_name)
int element_in_nucl_acid (char *res_name)
int is_water (char *res_name)
int is_valid_prot_element (const char *str, int ignore_case)
int is_valid_nucl_acid_element (const char *str, int ignore_case)
Function Documentation
int element_in_nucl_acid (char * res_name)
----------------------------------------------------------------------------- ## FUNCTION: int element_in_nucl_acid(char *res_name) ----------------------------------------------------------------------------- ## SPECIFICATION: Compare resname to the list of standard nucleic acid residues. Return 1 if resname is in this list, 0 else. ----------------------------------------------------------------------------- ## PARAMETRES: @ char *res_name : The current residue name ----------------------------------------------------------------------------- ## RETURN: int -----------------------------------------------------------------------------
Definition at line 355 of file pertable.c.
References ST_n_standard_nucl_acid_names, and ST_standard_nucl_acid_names.
Referenced by guess_element(), and set_atom_based_descriptors().
{
    int i;
    for(i=0;i<ST_n_standard_nucl_acid_names;i++){
        if(!strncmp(res_name, ST_standard_nucl_acid_names[i],3)) return 1;
    }
    return 0;
}
int element_in_std_res (char * res_name)
----------------------------------------------------------------------------- ## FUNCTION: int element_in_std_res(char *res_name) ----------------------------------------------------------------------------- ## SPECIFICATION: Compare resname to the list of standard protein resnames. Return 1 if resname is in this list, 0 else. ----------------------------------------------------------------------------- ## PARAMETRES: @ char *res_name : The current residue name ----------------------------------------------------------------------------- ## RETURN: int -----------------------------------------------------------------------------
Definition at line 333 of file pertable.c.
References ST_n_standard_res_names, and ST_standard_res_names.
Referenced by guess_element(), and set_atom_based_descriptors().
{
    int i;
    for(i=0;i<ST_n_standard_res_names;i++){
        if(!strncmp(res_name, ST_standard_res_names[i],3)) return 1;
    }
    return 0;
}
int is_valid_element (const char * str, int ignore_case)
## FUNCTION: is_valid_element
## SPECIFICATION: Check if a given string corresponds to an atom element.
## PARAMETERS: @ const char *str : The string to test @ int tcase : If = 1, dont take into account the case.
## RETURN: int: -1 if the strig is not an atom element, the index in the periodic table if so.
Definition at line 282 of file pertable.c.
References ST_nelem, ST_pte_symbol, and str_trim().
Referenced by check_is_valid_element(), and guess_element().
{
        if(str == NULL) return -1 ;
        if(strlen(str) <= 0) return -1 ;
        /* Use temporary variable to work on the string */
        int i ;
        char str_tmp[strlen(str)+1] ;
        strcpy(str_tmp, str) ;
        /* Remove spaces and case if asked*/
        str_trim(str_tmp) ;
        if(ignore_case == 1) {
                str_tmp[0] = tolower(str_tmp[0]) ;
                str_tmp[1] = tolower(str_tmp[1]) ;
        }
        /* Loop over */
        for (i = 0; i < ST_nelem ; i++) {
                char tmp[3] ;
                tmp[0] = ST_pte_symbol[i][0] ;
                tmp[1] = ST_pte_symbol[i][1] ;
                /* Remove case if asked */
                if(ignore_case == 1) {
                        tmp[0] = tolower(tmp[0]) ;
                        tmp[1] = tolower(tmp[1]) ;
                }
                tmp[2] = '\0' ;
                /* Do the comparison*/
                if(strcmp(str_tmp, tmp) == 0) return i ;
        }
        return -1 ;
}
int is_valid_nucl_acid_element (const char * str, int ignore_case)
----------------------------------------------------------------------------- ## FUNCTION: is_valid_nucl_acid_element ----------------------------------------------------------------------------- ## SPECIFICATION: Check if a given string corresponds to an atom element. ----------------------------------------------------------------------------- ## PARAMETERS: @ const char *str : The string to test @ int tcase : If = 1, dont take into account the case. ----------------------------------------------------------------------------- ## RETURN: int: -1 if the strig is not an atom element, the index in the periodic table if so. -----------------------------------------------------------------------------
Definition at line 437 of file pertable.c.
References ST_nucl_acid_nelem, ST_pte_nucl_acid_symbol, and str_trim().
Referenced by guess_element().
{
        if(str == NULL) return -1 ;
        if(strlen(str) <= 0) return -1 ;
        /* Use temporary variable to work on the string */
        int i ;
        char str_tmp[strlen(str)+1] ;
        strcpy(str_tmp, str) ;
        /* Remove spaces and case if asked*/
        str_trim(str_tmp) ;
        if(ignore_case == 1) {
                str_tmp[0] = tolower(str_tmp[0]) ;
                str_tmp[1] = tolower(str_tmp[1]) ;
        }
        /* Loop over standard protein element table*/
        for (i = 0; i < ST_nucl_acid_nelem ; i++) {
                char tmp[3] ;
                tmp[0] = ST_pte_nucl_acid_symbol[i][0] ;
                tmp[1] = ST_pte_nucl_acid_symbol[i][1] ;
                /* Remove case if asked */
                if(ignore_case == 1) {
                        tmp[0] = tolower(tmp[0]) ;
                        tmp[1] = tolower(tmp[1]) ;
                }
                tmp[2] = '\0' ;
                /* Do the comparison*/
                if(strncmp(str_tmp, tmp,1) == 0) return i ;
        }
        return -1 ;
}
int is_valid_prot_element (const char * str, int ignore_case)
----------------------------------------------------------------------------- ## FUNCTION: is_valid_prot_element ----------------------------------------------------------------------------- ## SPECIFICATION: Check if a given string corresponds to an atom element. ----------------------------------------------------------------------------- ## PARAMETERS: @ const char *str : The string to test @ int tcase : If = 1, dont take into account the case. ----------------------------------------------------------------------------- ## RETURN: int: -1 if the strig is not an atom element, the index in the periodic table if so. -----------------------------------------------------------------------------
Definition at line 384 of file pertable.c.
References ST_prot_nelem, ST_pte_prot_symbol, and str_trim().
Referenced by guess_element().
{
        if(str == NULL) return -1 ;
        if(strlen(str) <= 0) return -1 ;
        /* Use temporary variable to work on the string */
        int i ;
        char str_tmp[strlen(str)+1] ;
        strcpy(str_tmp, str) ;
        /* Remove spaces and case if asked*/
        str_trim(str_tmp) ;
        if(ignore_case == 1) {
                str_tmp[0] = tolower(str_tmp[0]) ;
                str_tmp[1] = tolower(str_tmp[1]) ;
        }
        /* Loop over standard protein element table*/
        for (i = 0; i < ST_prot_nelem ; i++) {
                char tmp[3] ;
                tmp[0] = ST_pte_prot_symbol[i][0] ;
                tmp[1] = ST_pte_prot_symbol[i][1] ;
                /* Remove case if asked */
                if(ignore_case == 1) {
                        tmp[0] = tolower(tmp[0]) ;
                        tmp[1] = tolower(tmp[1]) ;
                }
                tmp[2] = '\0' ;
                /* Do the comparison*/
                if(strncmp(str_tmp, tmp,1) == 0) return i ;
        }
        return -1 ;
}
int is_water (char * res_name)
Definition at line 363 of file pertable.c.
{
    if(!strncmp(res_name, "HOH",3)||!strncmp(res_name, "WAT",3)) return 1;
    return 0;
}
float pte_get_enegativity (const char * symbol)
## FUNCTION: pte_get_enegativity
## SPECIFICATION: Returns the electronegativity (Pauling) value for a given element
## PARAMETERS: @ const char *symbol: The symbol of the element in the periodic table
## RETURN: float: electrobegativity of Pauling corresponding to symbol
Definition at line 247 of file pertable.c.
References ST_nelem, ST_pte_electronegativity, and ST_pte_symbol.
Referenced by rpdb_read().
{
        char atom[3] = "" ;
        if (symbol != NULL) {
                atom[0] = (char) toupper((int) symbol[0]);
                atom[1] = (char) tolower((int) symbol[1]);
                atom[2] = '\0' ;
                int i ;
                for (i = 0; i < ST_nelem ; i++) {
                        if ( (ST_pte_symbol[i][0] == atom[0]) && (ST_pte_symbol[i][1] == atom[1]) ) {
                                return ST_pte_electronegativity[i] ;
                        }
                }
        }
        return -1 ;
}
float pte_get_mass (const char * symbol)
## FUNCTION: pte_get_mass
## SPECIFICATION: Returns the mass for a given element
## PARAMETERS: @ const char *symbol: The symbol of the element in the periodic table
## RETURN: float: mass corresponding to symbol
Definition at line 178 of file pertable.c.
References ST_nelem, ST_pte_mass, and ST_pte_symbol.
Referenced by rpdb_read().
{
        char atom[3] ;
        if (symbol != NULL) {
                atom[0] = (char) toupper((int) symbol[0]);
                atom[1] = (char) tolower((int) symbol[1]);
                atom[2] = '\0' ;
                int i ;
                for (i = 0; i < ST_nelem ; i++) {
                        if ( (ST_pte_symbol[i][0] == atom[0]) && (ST_pte_symbol[i][1] == atom[1]) ) {
                                return ST_pte_mass[i] ;
                        }
                }
        }
        return -1 ;
}
float pte_get_vdw_ray (const char * symbol)
## FUNCTION: pte_get_vdw_ray
## SPECIFICATION: Returns the van der walls radius for a given element
## PARAMETERS: @ const char *symbol: The symbol of the element in the periodic table
## RETURN: float: vdw radius corresponding to symbol
Definition at line 213 of file pertable.c.
References ST_nelem, ST_pte_rvdw, and ST_pte_symbol.
Referenced by rpdb_read().
{
        char atom[3] ;
        if (symbol != NULL) {
                atom[0] = (char) toupper((int) symbol[0]);
                atom[1] = (char) tolower((int) symbol[1]);
                atom[2] = '\0' ;
                int i ;
                for (i = 0; i < ST_nelem ; i++) {
                        if ( (ST_pte_symbol[i][0] == atom[0]) && (ST_pte_symbol[i][1] == atom[1]) ) {
                                return ST_pte_rvdw[i] ;
                        }
                }
        }
        return -1 ;
}