fpocket: sort.h File Reference
sort.h File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include "rpdb.h"
#include "voronoi.h"
#include "memhandler.h"
Data Structures
struct s_vect_elem
struct s_vsort
Defines
#define M_ATOM_TYPE 0
#define M_VERTICE_TYPE 1
#define M_SORT_X 1
#define M_SORT_Y 2
#define M_SORT_Z 3
Functions
s_vsort * get_sorted_list (s_atm **atoms, int natms, s_vvertice **pvert, int nvert)
void print_sorted_lst (s_vsort *lsort, FILE *buf)
void free_s_vsort (s_vsort *lsort)
Define Documentation
#define M_ATOM_TYPE 0
Definition at line 52 of file sort.h.
Referenced by merge_atom_vert(), partition_x(), and print_sorted_lst().
#define M_SORT_X 1
Definition at line 55 of file sort.h.
#define M_SORT_Y 2
Definition at line 56 of file sort.h.
#define M_SORT_Z 3
Definition at line 57 of file sort.h.
#define M_VERTICE_TYPE 1
Definition at line 53 of file sort.h.
Referenced by count_atm_prop_vert_neigh(), count_pocket_lig_vert_ovlp(), get_mol_ctd_atm_neigh(), get_mol_vert_neigh(), and merge_atom_vert().
Function Documentation
void free_s_vsort (s_vsort * lsort)
## FUNCTION: free_s_vsort
## SPECIFICATION: Free memory for s_vsort structure
## PARAMETRES: @ s_vsort *lsort: Structure to free
## RETURN:
Definition at line 328 of file sort.c.
References my_free(), and s_vsort::xsort.
Referenced by count_atm_prop_vert_neigh(), count_pocket_lig_vert_ovlp(), count_vert_neigh_P(), get_mol_atm_neigh(), get_mol_ctd_atm_neigh(), and get_mol_vert_neigh().
{
        if(lsort) {
                if(lsort->xsort) my_free(lsort->xsort) ;
                my_free(lsort) ;
        }
}
s_vsort* get_sorted_list (s_atm ** atoms, int natms, s_vvertice ** pvert, int nvert)
## FUNCTION: get_sorted_list
## SPECIFICATION: This function will return a lists which will contains all atoms and vertices sorted on x axis. First, we merge atom and vertice lists into those a single list. Then they will be sorted using a quickSort algorithm, using the x positions of vertices and atoms as criteria for sorting.
## PARAMETRES: @ s_pdb *pdb : PDB structure, basically containing atoms @ s_vvertice **pvert, int nvert : List of vertices (if NULL, only atoms will be sorted)
## RETURN: s_vsort*: pointer to the structure containing all sorted data (see .h)
Definition at line 86 of file sort.c.
References merge_atom_vert(), my_malloc(), s_vsort::nelem, qsort_dim(), and s_vsort::xsort.
Referenced by count_atm_prop_vert_neigh(), count_pocket_lig_vert_ovlp(), count_vert_neigh_P(), get_mol_atm_neigh(), get_mol_ctd_atm_neigh(), and get_mol_vert_neigh().
{
        s_vsort *lsort = (s_vsort *) my_malloc(sizeof(s_vsort)) ;
        lsort->nelem = 0 ;
        if(atoms) lsort->nelem += natms ;
        if(pvert) lsort->nelem += nvert ;
        if(lsort->nelem == 0) return NULL ;
        /* Allocate memory */
        lsort->xsort = (s_vect_elem*) my_malloc((lsort->nelem)*sizeof(s_vect_elem)) ;
        merge_atom_vert(lsort, atoms, natms, pvert, nvert) ;
        qsort_dim(lsort->xsort, lsort->nelem) ;
        return lsort ;
}
void print_sorted_lst (s_vsort * lsort, FILE * buf)
## FUNCTION: print_sorted_lst
## SPECIFICATION: Print one of the sorted tab of a s_vsort structure
## PARAMETRES: @ s_vsort *lsort : Structure containing tab @ FILE *buf : Buffer to print in.
## RETURN:
Definition at line 286 of file sort.c.
References M_ATOM_TYPE, s_vsort::nelem, s_vvertice::sort_x, s_atm::sort_x, s_vvertice::x, s_atm::x, and s_vsort::xsort.
{
        s_vect_elem *lst = NULL ;
        lst = lsort->xsort ; fprintf(buf, "\n========== Printing list of vertices and atoms sorted on X axe:\n") ;
        float cval, prev = -1.0 ;
        int i ;
        for(i = 0 ; i < lsort->nelem ; i++) {
                fprintf(buf, "> Element at %d: ", i);
                if(lst[i].type == M_ATOM_TYPE) {
                        s_atm *a = (s_atm*) lst[i].data ;
                        cval = a->x ;
                        fprintf(buf, " ATOM coord = %f, index stored: %d", cval, a->sort_x) ;
                }
                else {
                        s_vvertice *v = (s_vvertice*) lst[i].data ;
                        cval = v->x ;
                        fprintf(buf, " VERTICE coord = %f, index stored: %d", cval, v->sort_x) ;
                }
                if(prev > cval) fprintf(buf, " !!!!!!! ") ;
                fprintf(buf, "\n") ;
                prev = cval ;
        }
}