fpocket: voronoi_lst.h File Reference
voronoi_lst.h File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "voronoi.h"
#include "atom.h"
#include "memhandler.h"
Data Structures
struct node_vertice
struct c_lst_vertices
Functions
c_lst_vertices * c_lst_vertices_alloc (void)
node_vertice * node_vertice_alloc (s_vvertice *vertice)
node_vertice * c_lst_vertices_add_first (c_lst_vertices *lst, s_vvertice *vertice)
node_vertice * c_lst_vertices_add_last (c_lst_vertices *lst, s_vvertice *vertice)
void c_lst_vertices_free (c_lst_vertices *lst)
s_atm ** get_vert_contacted_atms (c_lst_vertices *v_lst, int *nneigh)
Function Documentation
node_vertice* c_lst_vertices_add_first (c_lst_vertices * lst, s_vvertice * vertice)
## FONCTION: c_vertice_lst_add_first
## SPECIFICATION: Add a vertice at the first position of the list.
## PARAMETRES: @ c_lst_vertices *lst : chained list of vertices @ s_vvertice *vertice : vertice to add
## RETURN: node_vertice *: pointer toi the new node.
Definition at line 123 of file voronoi_lst.c.
References c_lst_vertices::first, c_lst_vertices::n_vertices, node_vertice::next, node_vertice_alloc(), and node_vertice::prev.
{
        node_vertice *newn = NULL ;
        if(lst) {
                newn = node_vertice_alloc(vertice) ;
                lst->first->prev = newn ;
                newn->next = lst->first ;
                lst->first = newn ;
                lst->n_vertices += 1 ;
        }
        return newn ;
}
node_vertice* c_lst_vertices_add_last (c_lst_vertices * lst, s_vvertice * vertice)
## FONCTION: c_vertice_lst_add_last
## SPECIFICATION: Add a vertice at the end of the chained list
## PARAMETRES: @ c_lst_pocket *lst : chained list of pockets @ s_vvertice *vertice : vertice to add
## RETURN: node_vertice *: Pointer to the new node
Definition at line 154 of file voronoi_lst.c.
References c_lst_vertices::first, c_lst_vertices::last, c_lst_vertices::n_vertices, node_vertice::next, node_vertice_alloc(), and node_vertice::prev.
Referenced by extract_wanted_vertices(), and updateIds().
{
        struct node_vertice *newn = NULL ;
        if(lst) {
                newn = node_vertice_alloc(vertice) ;
                if(lst->last) {
                        newn->prev = lst->last ;
                        lst->last->next = newn ;
                }
                else {
                        lst->first = newn ;
                }
                lst->last = newn ;
                lst->n_vertices += 1 ;
        }
        return newn ;
}
c_lst_vertices* c_lst_vertices_alloc (void)
## FONCTION: lst_vertices_alloc
## SPECIFICATION: Allocate a list of vertices
## PARAMETRES:
## RETURN: c_lst_vertices*
Definition at line 71 of file voronoi_lst.c.
References c_lst_vertices::current, c_lst_vertices::first, c_lst_vertices::last, my_malloc(), and c_lst_vertices::n_vertices.
Referenced by extract_wanted_vertices(), and updateIds().
{
        c_lst_vertices *lst = (c_lst_vertices *)my_malloc(sizeof(c_lst_vertices)) ;
        lst->first = NULL ;
        lst->last = NULL ;
        lst->current = NULL ;
        lst->n_vertices = 0 ;
        return lst ;
}
void c_lst_vertices_free (c_lst_vertices * lst)
## FONCTION: lst_vertice_free
## SPECIFICATION: Free memory of a chained list
## PARAMETRES: @ c_lst_vertices *lst: list of voronoi vertices
## RETURN:
Definition at line 188 of file voronoi_lst.c.
References c_lst_vertices::current, c_lst_vertices::first, c_lst_vertices::last, my_free(), and node_vertice::next.
Referenced by dropPocket().
{
        //fprintf(stdout, "Freeing list of vertices\n") ;
        node_vertice *next = NULL ;
        if(lst) {
                lst->current = lst->first ;
                while(lst->current) {
                        next = lst->current->next ;
                        my_free(lst->current) ;
                        lst->current = next ;
        }
        }
        lst->first = NULL ;
        lst->last = NULL ;
        lst->current = NULL ;
        my_free(lst) ;
}
s_atm** get_vert_contacted_atms (c_lst_vertices * v_lst, int * nneigh)
## FUNCTION: get_vert_contacted_atms
## SPECIFICATION: Get the list of atoms contacted by each vertice in the given list of vertices.
## PARAMETRES: @ c_lst_vertices *v_lst : The list of vertices of the pocket. @ int *nneigh : OUTPUT A pointer to the number of neighbour found, will be modified
## RETURN: A tab of pointers to the pocket contacting atoms.
Definition at line 225 of file voronoi_lst.c.
References c_lst_vertices::first, s_atm::id, in_tab(), my_malloc(), c_lst_vertices::n_vertices, s_vvertice::neigh, node_vertice::next, and node_vertice::vertice.
Referenced by desc_pocket().
{
        int i ;
        int nb_neigh = 0 ;
        int atm_seen[v_lst->n_vertices * 4] ;
        s_atm **neigh = (s_atm **)my_malloc(sizeof(s_atm*)*v_lst->n_vertices * 4) ;
        node_vertice *cur = v_lst->first ;
        while(cur) {
                s_vvertice *vcur = cur->vertice ;
                for(i = 0 ; i < 4 ; i++) {
                /* For each neighbor, if this atom has not been see yet, add it. */
                        if(!in_tab(atm_seen, nb_neigh, vcur->neigh[i]->id)) {
                                neigh[nb_neigh] = vcur->neigh[i] ;
                                atm_seen[nb_neigh] = neigh[nb_neigh]->id ;
                                nb_neigh++ ;
                        }
                }
                cur = cur->next ;
        }
        *nneigh = nb_neigh ;
        return neigh ;
}
node_vertice* node_vertice_alloc (s_vvertice * vertice)
## FONCTION: node_vertice_alloc
## SPECIFICATION: Allocate memory for one vertice node.
## PARAMETRES: @ s_vvertice *vertice : pointer to the vertice to store in the node
## RETURN: node_vertice*: Allocated node
Definition at line 97 of file voronoi_lst.c.
References my_malloc(), node_vertice::next, node_vertice::prev, and node_vertice::vertice.
Referenced by c_lst_vertices_add_first(), and c_lst_vertices_add_last().
{
        node_vertice *n_vertice = (node_vertice *) my_malloc(sizeof(node_vertice)) ;
        n_vertice->next = NULL ;
        n_vertice->prev = NULL ;
        n_vertice->vertice = vertice ;
        return n_vertice ;
}