# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

if {[catch {
    package ifneeded multiseqdialog 1.0 "[list source [file join $dir download_updates.tcl]]\n[list source [file join $dir multiseqdialog.tcl]]\n[list source [file join $dir scrolledframe.tcl]]\n[list source [file join $dir wait_dialog.tcl]]"
} errorMessage] != 0} {
    
    global errorInfo
    set callStack [list "MultiSeq Error) " $errorInfo]
    puts [join $callStack "\n"]
}
