# Tcl package index file, version 0.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded cgtools 0.1 "set env(CGTOOLSDIR) [list $dir] ; source [list [file join $dir cgtools.tcl]]"
package ifneeded cggui 0.2 "set env(CGTOOLSDIR) [list $dir] ; source [list [file join $dir cggui.tcl]]"
package ifneeded cgnetworking 0.3 "set env(CGTOOLSDIR) [list $dir] ; source [list [file join $dir cgnetworking.tcl]]"
